### ISSUE TITLE
Alt+Shift+3 behaves weirdly

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/terminal#10244]
### Windows Terminal version (or Windows build number)

10.0.19041.985

### Other Software

WSL 1 & 2

### Steps to reproduce

1. Open WSL
2. Write "qwertyuiop" in the command line
3. Press <kbd>←</kbd> 5 times.
4. Press <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>3</kbd>
5. Press <kbd>q</kbd> 10 times.

### Expected Behavior

I expect the current input being commented when I press <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>3</kbd>

### Actual Behavior

You will see something like this:

![image](https://user-images.githubusercontent.com/29214635/119889433-d35a9400-bf36-11eb-8e1a-8e8f7f542694.png)
The 'q's overlap the prompt.

**Comment by adriancuadrado** [comment]
Please see this issue where I originally reported the bug: https://github.com/microsoft/WSL/issues/6989

**Comment by zadjii-msft** [comment]
> 10.0.19041.985

Okay, that's important to note. I'm not seeing this locally, but I'm on a much much newer build than that. I'm wondering if this is some VT sequence that bash is emitting that we've fixed since then. @j4james anything come to mind?

An easy way to test might be to install the Windows Terminal and try this again in that. The Terminal has an up-to-date version of the console shipped in it, that might be an easy sanity check.

**Comment by adriancuadrado** [comment]
@zadjii-msft https://github.com/microsoft/WSL/issues/6989#issuecomment-849962191

> ![image](https://user-images.githubusercontent.com/29214635/119899973-27b84080-bf44-11eb-9eb1-e083300b3bd0.png)
> Alt+Shift+3 seems to insert a bell character instead. Apart from that in the windows terminal everything works as expected.
> 
> Running wsl.exe in cmd leads to the same symptoms (the 'q' overlaps the prompt again).
> 
> I had [Ubuntu-20.04](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71?activetab=pivot:overviewtab), so I installed [Ubuntu](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6#activetab=pivot:overviewtab). Same problem.
> 
> I started to suspect it is just the fault of the cmd, so I run cmd and tried the same without wsl, but this insert the '·' character.
> 
> I doubt this is related, but I am using the Spanish keyboard layout:
> ![image](https://user-images.githubusercontent.com/29214635/119900739-35ba9100-bf45-11eb-8618-f2e870aef257.png)

**Comment by j4james** [comment]
I don't think it's a VT sequence - it looks like it's got something to do with the UTF-8 parsing. What's happening is that bash is outputting the byte `0xA3` at the point the `Alt+Shift+3` is typed. On the old version of conhost (build 18363 of Windows for me) that byte was simply dropped. On the current version of OpenConsole it is output as an error glyph.

And when you're inserting characters into the middle of a line in bash, it updates the display by backspacing over the characters that were previously output, and then writing out the new ones. In this case it ends up backspacing too far, because it was expecting the `0xA3` to have occupied one cell rather than being dropped.

Simple test case: `printf "*\xA3*\n"`

On the old version of conhost that outputs `**`. On the latest version you get `*�*` (or something of that sort).

**Comment by carlos-zamora** [comment]
@adriancuadrado @j4james are you still seeing this issue?

We just tested it and (in the great words of software development) "it works on my machine". Closing this for now, but if you're still experiencing it, let me know and I'll gladly reopen it. :)

**Comment by j4james** [comment]
@carlos-zamora It's still broken on my inbox conhost (now on version 10.0.19044.2006 of Windows), and still working in OpenConsole. So whatever the fix was, it clearly hasn't made it to my version of Windows 10. And I was under the impression you're only releasing conhost updates for Windows 11 now, so I suspect it may never be fixed.

**Comment by adriancuadrado** [comment]
My Windows 10 build version is 19043.2130 and I still have the same problem.

**Comment by DHowett** [comment]
The thing that's most surprising to me is that I can't reproduce this on any of the following console versions:

| Version                     | Does `Alt+Shift+3` Work? |
| --------------------------- | ------------------------ |
| 10.0.17134.1                | ✅                       |
| 10.0.17763.1                | ✅                       |
| 10.0.18362.1                | ✅                       |
| 10.0.19041.1                | ✅                       |
| 10.0.22000.1                | ✅                       |
| 10.0.22621.1                | ✅                       |
| OpenConsole at v1.17.2982.0 | ✅                       |

Are either of you using a non-US keyboard layout? I wonder if something is triggering "number pad event synthesis" and resulting in a numpad event like `Alt + 1 2 3`...

**Comment by j4james** [comment]
> Are either of you using a non-US keyboard layout?

Yeah, sorry I should have mentioned that. I'm using a UK keyboard.

But note that that's only half the problem. Regardless of what keyboard you're using, I would expect that the `printf "*\xA3*\n"` test case I mentioned above to be generating 3 cells of output. That's correct in OpenConsole but not in my current inbox conhost.

**Comment by adriancuadrado** [comment]
@DHowett I am using the Spanish keyboard layout.

**Comment by zadjii-msft** [comment]
Hey this somehow fell off our triage queue. It's been like two years now - is this still happening/?

**Comment by j4james** [comment]
If you're referring to the weird q overwriting thing, that's still reproducible for me on Windows 10 build 19045.4170, but I assumed the Windows 10 conhost wasn't being updated anymore, so that's to be expected. It works fine in the latest OpenConsole (and that's been the case for years). I assume the conhost on Window 11 would be fine as well.

**Comment by zadjii-msft** [comment]
Well, good enough for me. Sorry for losing this one!
