### ISSUE TITLE
Bug Report: Green Screen of Death when acessing settings from within console

### ISSUE THREAD

**Issue by mrmikeman38** [microsoft/terminal#1112]
# Environment

```none
Windows build number: 10.0.18362.145
Windows Terminal version (if applicable):
```

# Steps to reproduce
-Open "Windows Terminal (dev build)"
-Open the dropdown menu
-Select "Settings" from dropdown menu

# Expected behavior
"Profiles.json" is opened

# Actual behavior
Windows crashes to a Green Screen of Death with stop code APC_INDEX_MISMATCH

No further information presented.

**Comment by zadjii-msft** [comment]
Well that's insanely bad. I thought we fixed this with the `EnableMouseInPointer` thing, but this might be something else.

Actually, thinking on it more, this might be something else entirely. The `EnableMouseInPointer` thing was for `Alt+a` causing a GSOD.

**Comment by zadjii-msft** [comment]
For the record, I can't get this to repro locally, so if I could get another verification of this bug report, that'd be appreciated.

**Comment by mrmikeman38** [comment]
For the record, it might be unrelated but Microsoft Word also causes a GSOD on build 1903.

**Comment by DHowett-MSFT** [comment]
@mrmikeman38 Thanks for the report. Would you mind collecting a memory dump (see [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/enabling-a-kernel-mode-dump-file) for brief instructions on enabling that _if_ it's not already enabled) and e-mailing it to secure@microsoft.com? Mention my name ("Dustin Howett") as somebody who they should route it to.

**Comment by KennethVanMele** [comment]
Is it possible to reopen this because this is still a problem. Just installed.
Winver: 18362.175
Windows Terminal: 0.2.1715.0

**Comment by Yoanndp** [comment]
I can provide information about it, I have done the exact same thing as the owner and I got a bsod.
Informations:

**Computer basic informations:**
Windows 10 Pro x64
Version 1903 (Build: 18362.175)

**BSOD informations:**
_Bug Check String:_
• APC_INDEX_MISMATCH
_Bug Check Code:_
• 0x00000001
_Caused By Driver:_
• ntoskrnl.exe
_Caused By Address:_
• ntoskrnl.exe+1bc8a0

Here is my full Bsod dump uploaded on WeTransfer.com
https://we.tl/t-X23Ccy1nmA
