### ISSUE TITLE
warning font not found 

### ISSUE THREAD

**Issue by charudatta10** [microsoft/terminal#11583]
### Windows Terminal version (or Windows build number)

Windows Terminal Version: 1.11.2921.0

### Steps to reproduce

when Windows Terminal terminal is opend it shows warning saying missing fonts when fonts is already installed and it gets resolved once profile clicked and saved again.

<img width="810" alt="Screenshot_terminal_bug" src="https://user-images.githubusercontent.com/10682378/138511772-aa1a95f1-1825-48c3-b89b-44866a735b5e.png">

### Expected Behavior

fonts should be loaded 

### Actual Behavior

font is found missing

**Comment by zadjii-msft** [comment]
This seems a lot like #12079, there might be something eschew here.

**Comment by charudatta10** [comment]
yes @zadjii-msft #12079  is same issue.

**Comment by charudatta10** [comment]
@zadjii-msft  the tried both methods first directaly downloading  .ttf file and install fonts globally it gave error so i uninstalled it and added locally using scoop installer still same isuue.

**Comment by 9point6** [comment]
@zadjii-msft I'm also experiencing this with all of these variants ([from here](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode)):

* `FiraCode NF`
* `FiraCode NF Retina`
* `FiraCode Nerd Font`
* `FiraCode Nerd Font Retina`
* `FiraCode Nerd Font Mono Retina`

Previously I was able to go into the settings and just select it again, and it'd work on pressing save. The latest version (1.12.10908.0) seems to also break this workaround.

This issue needs to be re-opened

**Comment by charudatta10** [comment]
@[9point6](https://github.com/9point6) The bug is still there. 

Solution : The problem is resolved if font.ttf file is installed for all users.

**Comment by luyiyun** [comment]
This problem still exists and I also met it. So how i can solve it?

**Comment by luyiyun** [comment]
I restarted the terminal and the problem was solved.

**Comment by contento** [comment]
This is an annoying issue that comes and goes. I'm not sure what triggers it but the font is installed, and it suddenly starts to pop up.

**Comment by zadjii-msft** [comment]
@contento You might want to refer to https://github.com/microsoft/terminal/issues/14231#issuecomment-1280827973

**Comment by darekjk** [comment]
I had the same issue on WIn11 Iwith all updates) and found that problem was with the FontCache service.
So I stopped it:
sc stop "FontCache"
sc config "FontCache" start=disabled

And now all new installed fonts works fine in Windows Terminal sessions. 
PS: I tried rebuild the font cache service earlier but after each reboot problem came back.

**Comment by soundlake** [comment]
Thank you, @darekjk It works for me.

> I had the same issue on Win11 Iwith all updates) and found that problem was with the FontCache service. So I stopped it: sc stop "FontCache" sc config "FontCache" start=disabled

For plain Windows users like me, the two commands @darekjk mentioned work in cmd.

**Comment by the-simian** [comment]
@darekjk 's solution worked, I needed to run CMD as admin

**Comment by hellfirehd** [comment]
It is now 2025 and I am still encountering this issue. Stopping and disabling FontCache resolved it, but I feel like that is kludgy.
