### ISSUE TITLE
split-pane --startDirectory fails, -d is ignored

### ISSUE THREAD

**Issue by ytqsl** [microsoft/terminal#12423]
### Windows Terminal version

1.12.10334.0

### Windows build number

10.0.22000.0

### Other Software

PowerShell 7.2.1 as default profile

### Steps to reproduce

`wt sp --startDirectory C:\Users\`
`wt sp --startDirectory .\`
`wt sp -d .\`

### Expected Behavior

pane opens in the specified directory

### Actual Behavior

`wt sp -d .\`: pane is opened with default pwsh location (system32 if not changed with set-location))
`wt sp --startDirectory C:\Users\`: [error 2147942405 (0x80070005) when launching `C:\Users\']

**Comment by zadjii-msft** [comment]
`wt sp -d .` will work the way you want. 

It's a little weird that `wt sp -d .\` starts in `C:\Windows\System32`, that might need some looking in to. 

Otherwise, the long form of the arg you're looking for is [`--startingDirectory`](https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows#split-pane-command), not `--startDirectory`

**Comment by ytqsl** [comment]
Looks like -d and --startingDirectory both behave the same way currently (I typed it wrongly before).

[this](https://raw.githubusercontent.com/bcgov/embc-ess-mod/master/wt-responders.ps1) used to work until few days ago.

**Comment by zadjii-msft** [comment]
I actually think this is fixed in `main`, in #13706

**Comment by ytqsl** [comment]
Actually, I just tested with version 1.15.2524.0 + PowerShell 7.2.6,  and even a simple `wt -d c:\` is not working as expected - the working directory is always home. Changing the PowerShell profile to `Use parent process directory` made no difference.

**Comment by zadjii-msft** [comment]
Wait is this still an issue/? I just tried a 

* `wt -d C:\`
* `wt sp -d C:\Users\`
* `wt sp -d .\`
* ```wt sp -d .\ `; sp -d .\src```

all from a PowerShell prompt, with 1.20.2683.0 (≅ 1.19 preview), and they all worked exactly as expected. If these aren't working on 1.19, I'm guessing we'll probably need to see your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)?

**Comment by ytqsl** [comment]
Still the same for me: from pwsh 7.3.7 run `wt -d c:\` and a new tab is opened and the directory is ~.
[settings.zip](https://github.com/microsoft/terminal/files/12771163/settings.zip)

**Comment by zadjii-msft** [comment]
Hmm... does `wt -p "Command Prompt" -d c:\` work as expected?

Here's an interesting question - what's in your PowerShell `$profile`? Maybe there's something in there that's `cd`-ing to `~`/?

**Comment by ytqsl** [comment]
`wt -p "Command Prompt" -d c:\` worked.

Yes, I had `set-location $HOME` for some reason, removing this line fixed it. As it was synching using OneDrive, it also explains why it was the same behaviour in all my machines :).

Thanks, I'll close it.

**Comment by zadjii-msft** [comment]
Hey that's good news! At least we got to the root cause of this (after more than a year 😅)
