### ISSUE TITLE
Get Chinese characters ghost in display when use TUI program

### ISSUE THREAD

**Issue by lfishRhungry** [microsoft/terminal#12479]
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.0

### Other Software

lf r26
fzf 0.29.0
lazygit 0.32.2
powershell 7

### Steps to reproduce

install these console TUI software in windows terminal，and just use them interacting with some files in Chinese characters.

### Expected Behavior

display characters normally

### Actual Behavior

https://user-images.githubusercontent.com/52651594/153695246-fe916770-2e6c-4730-84b2-d425bc157e31.mp4

**Comment by lhecker** [comment]
To reproduce this:
* Install [`lf`](https://github.com/gokcehan/lf#installation) (I can give you a prebuilt binary)
* Clone https://github.com/forthespada/InterviewGuide
* Navigate through the various .md files in that project

This issue occurs in cmd.exe, but doesn't occur in WSL.
This makes me suspect that this is an issue in `lf` and not in Windows Terminal.

**Comment by zadjii-msft** [comment]
Hey @lfishRhungry can you help clarify? Which part is unexpected? the glyph size, or the fact that the glyphs remain on the screen at all?

These two frames follow one another:
![image](https://user-images.githubusercontent.com/18356694/154300305-57367c59-43f4-43a7-bba4-fbc5b33dffa7.png)
![image](https://user-images.githubusercontent.com/18356694/154300441-57d1775c-017a-4563-8277-db7f6bf88b26.png)


The wrongly sized glyphs in the second image are present in the first image. That makes us think they were supposed to be replaced with whitespace, but instead the buffer got corrupted.

https://github.com/gokcehan/lf/issues/451 seems to imply this should have been fixed in r17? 

https://github.com/gokcehan/lf/issues/644 was filed in 2021, which sounds like the same thing. That issue was closed by the OP without giving an answer. I'd recommend following up there. 

/dup https://github.com/gokcehan/lf/issues/644

**Comment by SpicyChickenFLY** [comment]
Hi @zadjii-msft I think this issue should be reconsidered

[gokcehan/lf#644](https://github.com/gokcehan/lf/issues/644) is not solved yet. 
Enable `legacy console` does make some effect to eliminate some ghost CJK characters. However there are still some ghost characters on display.
Before:
![image](https://user-images.githubusercontent.com/24915018/155937281-2c05c028-2f07-406e-a30f-014c8da6a225.png)
 After:
![image](https://user-images.githubusercontent.com/24915018/155937427-55e2d570-2568-4510-9a20-991cb2c7af3e.png)

Simular problems occured in
* lf (tcell)
* fzf (tcell)
* lazygit(gocui->termbox) 
* lazydocker(gocui->termbox) 
These repos use different TUI dependencies, so maybe this problem is not caused by repos listed below.
 
This makes me suspect that this is an issue occurred when running TUI program coded in Golang in Console_Prompt/PowerShell/Windows_Terminal.

**Comment by lfishRhungry** [comment]
You can open a new issue.
I had change my operation system to linux.😅😅😅Hope to learn more.

**Comment by bluepongo** [comment]
May I ask, what is the progress of solving this problem? I have the same problem.

**Comment by zadjii-msft** [comment]
We haven't really investigated more.  We'll make sure to update this thread when there are updates to share. In the meantime, might I recommend the Subscribe button?
![image](https://user-images.githubusercontent.com/18356694/91237459-5cbb0c80-e700-11ea-9347-b9b1ec2813b1.png)
That way you'll be notified of any updates to this thread, without needlessly pinging everyone on this thread ☺️

**Comment by CnTeng** [comment]
I have the same problem, too.

**Comment by zadjii-msft** [comment]
pre-emptively putting into 1.19 to see if Atlas v9000 solved this. I don't _think_ so. I'm still under the impression that this is fundamentally an issue down in tcell. The glyph rendering looks a LOT better in the latest 1.18 builds, but something is absolutely choking on the wide chars.

**Comment by zadjii-msft** [comment]
Looks like the new renderer in 1.18 did end up fixing this after all:

![gh-12479-fixed](https://github.com/microsoft/terminal/assets/18356694/81824b6a-274b-4297-a6b7-ea8c2fba7c4a)
