### ISSUE TITLE
Unable to find the selected font CaskaydiaCove NF

### ISSUE THREAD

**Issue by va-it** [microsoft/terminal#12587]
**N.B. I have looked at the other font related issues (e.g. #11648), but I believe mine is slightly different. In my case, the Cascadia Mono font is found without problems.** 

This issue is occurring in both Terminal and Terminal Preview. I have the CaskaydiaCove NF font installed and I am able to use it on other apps such as WordPad. However, upon starting the Terminal, I receive the "Unable to find the selected font" error.

The problem is temporarily resolved by simply opening the settings and saving, even without changing anything. But then the error is presented once more when the program is closed and opened again.

Windows Terminal Version: 1.12.10393.0
Windows Terminal Preview Version: 1.13.10395.0

![terminal_error](https://user-images.githubusercontent.com/46725213/155850436-ca5f3da2-50b1-44db-8466-465ea50bcc3c.png)

![terminal_fonts](https://user-images.githubusercontent.com/46725213/155850427-ac0a3626-1c7e-4cbf-86aa-b1a5e1102f26.png)

**Comment by zadjii-msft** [comment]
Hmm. This sounds like #9360, but that was duped to #9375 which was supposed to be fixed like, months ago. 

Maybe this is a variant of the thing in PR at #12554? (Mind confirming for me @lhecker?)

**Comment by lhecker** [comment]
> Maybe this is a variant of the thing in PR at https://github.com/microsoft/terminal/pull/12554? (Mind confirming for me @lhecker?)

Hmm... no, on Windows 11 this should've worked. The experimental text rendering engine doesn't support proper font fallback, which is why this can't be it either (WT crashes instead of presenting a Warning popup).
This is probably an unrelated issue.

**Comment by lhecker** [comment]
Here's what I did:
* Visit https://www.nerdfonts.com/font-downloads
* Download "Cascadia Code" aka "CaskaydiaCove"
* Install `Caskaydia Cove Nerd Font Complete Mono Windows Compatible.ttf`
* Set `font.face` to `"CaskaydiaCove NF"`

The result: It works!
![image](https://user-images.githubusercontent.com/2256941/156055648-ef9ae925-c644-439c-abc4-d406ddd63f37.png)

Unfortunately this means that I can't reproduce your issue in neither 1.12 nor 1.13.

**Comment by va-it** [comment]
> Here's what I did:
> 
> * Visit https://www.nerdfonts.com/font-downloads
> * Download "Cascadia Code" aka "CaskaydiaCove"
> * Install `Caskaydia Cove Nerd Font Complete Mono Windows Compatible.ttf`
> * Set `font.face` to `"CaskaydiaCove NF"`
> 
> The result: It works! ![image](https://user-images.githubusercontent.com/2256941/156055648-ef9ae925-c644-439c-abc4-d406ddd63f37.png)
> 
> Unfortunately this means that I can't reproduce your issue in neither 1.12 nor 1.13.

Thanks a lot for looking into this guys. I am not sure why I was having that issue, but I have followed the steps described and now I cannot replicate it either.

Sorry for wasting your time, but the issue is now resolved so thanks a lot again 🙏.

**Comment by lhecker** [comment]
@va-it Can you check the old legacy Fonts control panel? You can find it in the start menu by typing "Fonts".
If it's there I'd suggest removing the font and adding it back in.

**Comment by va-it** [comment]
> @va-it Can you check the old legacy Fonts control panel? You can find it in the start menu by typing "Fonts". If it's there I'd suggest removing the font and adding it back in.

Ok, so I deleted the font via the Control Panel and installed it again. Predictably, I could see the font in various apps and the new Settings, and I was able to use it in Terminal. 
Then I have restarted the computer, and again the font is not visible in Settings and cannot be used in Terminal. 
When I try to install it again (without removing it first from Control Panel) then I get told that it's already installed.

I believe something is wrong with Windows 11...

**Comment by lhecker** [comment]
@va-it Is your "Windows Font Cache Service" running? Which .ttf file from the nerd fonts collection are you using specifically?

**Comment by va-it** [comment]
The service is running and the .ttf is the one you suggested yesterday: _Caskaydia Cove Nerd Font Complete Mono Windows Compatible.ttf_

![image](https://user-images.githubusercontent.com/46725213/156224468-33477547-70a5-48c3-80a0-468e6daf157f.png)

**Comment by lhecker** [comment]
I can find various internal feedback that fonts are lost after a restart. One particular issue seems to occur if you install fonts via drag and drop in the settings app. Are you installing these fonts using this?
![image](https://user-images.githubusercontent.com/2256941/156226609-6cfed568-f203-476f-aebb-71f9cd1dc4c4.png)

If it works correctly, fonts should end up in `C:\Users\<username>\AppData\Local\Microsoft\Windows\Fonts`.
If they aren't there, something is wrong...

**Comment by zadjii-msft** [comment]
something makes me think this is like #3257

**Comment by lhecker** [comment]
@va-it I'll try to escalate one of the internal issues we have, or create on based on the information you've given us.
In the meantime I'll close this issue and if anything comes up I'll report back here. 🙂

**Comment by AkariiinMKII** [comment]
I've suffered this issue since updated to Windows 11, I believe that's the problem of system. Fortunately restarting font cache service solves this on my machine till next boot up.

**Comment by Yastruhank** [comment]
> I've suffered this issue since updated to Windows 11,

I've suffered this issue since I updated my Windows 11 to 22H2 too. I guess this is the problem of update with Windows 11.

**Comment by teeroddesigns** [comment]
I have the same issue. Restarting the Windows Font Cache Service also works for me.

**Comment by fredizzimo** [comment]
For me it also started after the Window 11 22H2 update. It seems like it looses all user installed fonts. 

The old control panel still shows the fonts, but they are missing from the new set settings Personalization/Fonts and Windows programs.

Like above, restarting the Windows Font Cache Service, seems to make it work again.

**Comment by alecthegeek** [comment]
I now have this problem, and restarting the Font Cache Service did not fix it :-(.

Happy to run any diagnostics people suggest, meanwhile I will keep pooking it

**Comment by GlennWo** [comment]
I was having this problem as well on Windows 11. I tried lots of things which stopped working after reboot. I finally found this solution which worked for me.

https://answers.microsoft.com/en-us/windows/forum/all/solution-installed-fonts-disappearing-after/146f4039-47c3-4017-a9b1-76f72badce39

1. Press Windows Key + R to open the Run dialog
2. Paste %appdata%\..\Local\Microsoft\Windows\Fonts and press Enter
3. You should see all your installed fonts, press Ctrl + A to select all the font files
4. While all the files are selected, right click any one of the files and press "Install for all users", not "Install" (with the shield icon, requires administrator privileges)

**Comment by johanvanmol** [comment]
Thank you @GlennWo .  This worked for me.  Like a lot of other commenters, I was restarting the FontCacheService at least daily.  I even created a small batch script for this.  Your solutions is way better: a one time fix that takes care of this problem.

**Comment by ChromaticRanger** [comment]
> I was having this problem as well on Windows 11. I tried lots of things which stopped working after reboot. I finally found this solution which worked for me.
> 
> https://answers.microsoft.com/en-us/windows/forum/all/solution-installed-fonts-disappearing-after/146f4039-47c3-4017-a9b1-76f72badce39
> 
> 1. Press Windows Key + R to open the Run dialog
> 2. Paste %appdata%..\Local\Microsoft\Windows\Fonts and press Enter
> 3. You should see all your installed fonts, press Ctrl + A to select all the font files
> 4. While all the files are selected, right click any one of the files and press "Install for all users", not "Install" (with the shield icon, requires administrator privileges)

A small addition. If you try this and get confused that you are not seeing "Install for all users". You need to be holding down the Shift key when right clicking on the selected files. You will then see that option in the displayed menu.

**Comment by MrKomputerKid** [comment]
> I was having this problem as well on Windows 11. I tried lots of things which stopped working after reboot. I finally found this solution which worked for me.
> 
> https://answers.microsoft.com/en-us/windows/forum/all/solution-installed-fonts-disappearing-after/146f4039-47c3-4017-a9b1-76f72badce39
> 
>     1. Press Windows Key + R to open the Run dialog
> 
>     2. Paste %appdata%..\Local\Microsoft\Windows\Fonts and press Enter
> 
>     3. You should see all your installed fonts, press Ctrl + A to select all the font files
> 
>     4. While all the files are selected, right click any one of the files and press "Install for all users", not "Install" (with the shield icon, requires administrator privileges)

Amazing! Thank you! This worked for me on my PC at home! Once again thank you!

**Comment by 4N7** [comment]
The replies in this issue contain a malformed path.
Here's the instructions with the correct path and pretty formatting 🙂:

1. Press <kbd>⊞ Win</kbd> + <kbd>R</kbd> to open the Run dialog
2. Paste `%appdata%\..\Local\Microsoft\Windows\Fonts` and press <kbd>Enter</kbd>
3. You should see all your installed fonts in file explorer. Select the desired font(s) (press <kbd>Ctrl</kbd> + <kbd>A</kbd> to select all).
4. With the desired fonts selected, right-click one of the files and click "*Install for all users*" (**NOT** "*Install*") next to the shield icon (requires administrator privileges). If you do not see "*Install for all users*", hold down <kbd>Shift</kbd> before right-clicking.

**Comment by Hoernchen** [comment]
This is still a problem, btw. Maybe adding a hint to the error popup would help?

**Comment by DHowett** [comment]
> This is still a problem, btw. Maybe adding a hint to the error popup would help?

Which version of Terminal are you on? We just published an update that should fix this.

**Comment by Hoernchen** [comment]
The current store version, 1.18.2822.0 - it is too late to try the preview, because I manually fixed it as described in https://github.com/microsoft/terminal/issues/12587#issuecomment-1364533486

**Comment by anatilopan** [comment]
> Which version of Terminal are you on? We just published an update that should fix this.

Hello, I have the same issue (and some of my friends too). After testing a theory.. I found out that only the versions installed via Microsoft Store have this issue. 
I tried the preview (v.  1.19.231113002-preview) version installed from ms. store and the same issue appeared;
Tired the preview version manually downloaded and put under program files directory (to be in the same zone as the ms. store one) and I could not reproduce the issue.
Same for the current stable version (v.  1.18.3181.0)

So I have new theories but i cannot confirm them right now as i do not own a Windows machine myself. (the one I`ve tested the theory is from work and i cannot make the necessary changes on it)
1. Somewhere the way that store apps are run/installed does not have the proper permissions to check user's installed fonts.
2. There is some GPO/administrative setting in my company that restricts store apps to have access to the fonts. 

There could be other things but frankly, i`m not a windows user and do not know a lot about it.. and i do not have a lot of time for testing those issues right now even if i`m an administrator on this machine, sorry for that.

Hope it helps somewhat... Have a nice day! ^^

**Comment by Gonkers** [comment]
> > This is still a problem, btw. Maybe adding a hint to the error popup would help?
> 
> Which version of Terminal are you on? We just published an update that should fix this.

I just decided to try Oh-My-Posh and I ran into this issue today.  I had to install the fonts into `c:\windows\fonts` in order to get this working. I have installed Windows Terminal via `winget`
Windows Terminal Preview
Version: 1.19.3172.0

Windows 11 23H2

**Comment by NewtonChutney** [comment]
I have recently been seeing more of this issue:

```
Unable to find the selected font "FiraCode Nerd Font Mono".

"Consolas" has been selected instead.

Please either install the missing font or choose another one.
```

WT version: `Windows Terminal - Version: 1.18.3181.0`
winver - `Microsoft Windows [Version 10.0.22631.2861]`

Looks like whatever fix was pushed didn't completely solve the issue..

<details>
<summary>
I installed the fonts by dragging and dropping into the fonts section in both control panel and Settings UWP.
I see that the fonts are installed in `%LOCALAPPDATA%\Microsoft\Windows\Fonts`. They are still visible in control panel after a restart, but not in Settings UWP. 
</summary>
<hr>

> Settings UWP:

![image](https://github.com/microsoft/terminal/assets/70827815/26cef1d4-4fb1-4358-a098-f59aafaea1a4)
<hr>

> %LOCALAPPDATA%\Microsoft\Windows\Fonts:

![image](https://github.com/microsoft/terminal/assets/70827815/c85c6cf3-3447-4ea1-ac99-3bfaa8721536)
<hr>

> Control panel

![image](https://github.com/microsoft/terminal/assets/70827815/0fb96166-7d4f-4f99-b697-a4d910456cc1)

</details>

**Comment by lhecker** [comment]
> Looks like whatever fix was pushed didn't completely solve the issue..

Just to be clear, this was never fixed by us. It's a bug in Windows font handling code and affects any store application. Follow these steps instead: https://github.com/microsoft/terminal/issues/12587#issuecomment-1364533486
To add, you should also make sure to delete all fonts from `%LOCALAPPDATA%\Microsoft\Windows\Fonts` if you can, since those don't work consistently correct anyways.

**Comment by dlplenin** [comment]
I had the same issue (with a different font) after installing Docker on Windows 11.

The solution was to reset the app:
![image](https://github.com/user-attachments/assets/234b7f66-aa07-4fab-8d46-5d213e743310)

I hope this helps someone in a similar situation.

**Comment by DonutWrecker** [comment]
> I had the same issue (with a different font) after installing Docker on Windows 11.
> 
> The solution was to reset the app: ![image](https://private-user-images.githubusercontent.com/2582026/356339878-234b7f66-aa07-4fab-8d46-5d213e743310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyODkxMTIsIm5iZiI6MTcyMzI4ODgxMiwicGF0aCI6Ii8yNTgyMDI2LzM1NjMzOTg3OC0yMzRiN2Y2Ni1hYTA3LTRmYWItOGQ0Ni01ZDIxM2U3NDMzMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTEyMDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjg5Mjc0NjlkNmQ1NmRkODVjOWI0MDJmM2E4ZDBmYmExMjM2ZTA4YWM2N2MyMTY5M2UzNzEyZWQ2ZjY4MGNmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PUzpD9JZMIz3SlY5vMx0acx249XRGnT1evnwiIMI8uI)
> 
> I hope this helps someone in a similar situation.

When you restart the Terminal, the problem emerges again. However, stopping and then starting the Windows Font Cache Service appears to have solved the issue, until the pc restart. You have to restart the Windows Font Cache Service everytime you restart your pc. What a downer.

**Comment by DonutWrecker** [comment]
https://github.com/microsoft/terminal/issues/14231#issuecomment-1280827973

The solution in the link solved my issue.

**Comment by ignatirabo** [comment]
[The problem still exists. The fix was 

> I was having this problem as well on Windows 11. I tried lots of things which stopped working after reboot. I finally found this solution which worked for me.
> 
> https://answers.microsoft.com/en-us/windows/forum/all/solution-installed-fonts-disappearing-after/146f4039-47c3-4017-a9b1-76f72badce39
> 
>     1. Press Windows Key + R to open the Run dialog
> 
>     2. Paste %LOCALAPPDATA%\Microsoft\Windows\Fonts and press Enter
> 
>     3. You should see all your installed fonts, press Ctrl + A to select all the font files
> 
>     4. While all the files are selected, right click any one of the files and press "Install for all users", not "Install" (with the shield icon, requires administrator privileges)

](https://github.com/microsoft/terminal/issues/12587#issuecomment-1364533486)

Comment above fixed the issue. Problem is still present with Terminal 1.21.2911.0

**Comment by SteveWyntontje** [comment]
The issue is also present in v1.22.11141.0.
