### ISSUE TITLE
"cmd.exe" does not exit the terminal properly if the last command didn't exit with 0

### ISSUE THREAD

**Issue by dovholuknf** [microsoft/terminal#13814]
### Windows Terminal version

1.14.1963.0

### Other Software

cme.exe - whatever comes with windows 11 latest

### Steps to reproduce

* set windows terminal preview as the default terminal application and save that setting
* hit the start key
* type: cmd.exe [enter] (to open "Command Prompt - App")
* type: type bob
* i expect you'll see: "The system cannot find the file specified."
* type: exit

### Expected Behavior

the terminal should exit

### Actual Behavior

the terminal stays alive indicating:
```
C:\Users\user_name>exit

[process exited with code 1 (0x00000001)]
```

**Comment by DHowett** [comment]
Thanks for the report! This has been fixed as of 1.15 builds 200x+. /dup #13325.

**Comment by dovholuknf** [comment]
![image](https://user-images.githubusercontent.com/46322585/186146746-f3ee394a-fd2e-4c42-96d1-f65e4093a14c.png)

the steps to report a bug are incorrect if you're using the terminal preview. turns out i am running 1.15.2003.0 and the bug is most definitely still present

**Comment by dovholuknf** [comment]
@DHowett - would you mind reopening/retriaging this bug? or i can just file another if i have to?

**Comment by zadjii-msft** [comment]
Sorry, more correctly, this is fixed in `Preview v1.15.228`, which should also be appearing by default on some set of stable builds also, but those haven't been spun up quite yet. 

It's enabled by a small change to the `closeOnExit` setting, which might have already been persisted as `graceful` in your settings. After #13560 is released, the new default should be `automatic`, which will do what you want. Till then, you can use `closeOnExit: always`

**Comment by dovholuknf** [comment]
Good grief - I had found/used `closeOnExit": "always"` for other profiles but didn't apply it to `'defaults"`... Which i just rectified, thanks!
```
        "defaults": 
        {
            "closeOnExit": "always",
            ...
            ...
```
