### ISSUE TITLE
Tab bar flickering randomly on both stable and preview version

### ISSUE THREAD

**Issue by poqdavid** [microsoft/terminal#14384]
### Windows Terminal version

1.16.2642.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Just by normal usage but also sometimes it's triggered more when the app loses and gains focus 

### Expected Behavior

Expecting the tab bar not to flicker

### Actual Behavior

Windows Terminal tab bar flickers randomly
![WindowsTerminal_2022-11-12_17-14-47](https://user-images.githubusercontent.com/9592210/201533459-31924762-03d8-4f63-a5cd-81d728953039.gif)

**Comment by poqdavid** [comment]
Also want to add that all drivers are updated and this happens with both iGPU and dedicated Nvidia GPU
and wanted to mention I have both Stable and Preview versions installed

**Comment by 237dmitry** [comment]
Is this only in pwsh? What if run it with `-noprofile` or temporary reset the prompt function `function prompt { "PS $pwd> " }`

**Comment by zadjii-msft** [comment]
This just looks like a bug with acrylic itself. Can you file feedback via the Feedback Hub? I don't know what the area path for that might be... maybe Composition? Effects? Not sure if those are real paths. 

I suspect this might get better with #13935. The "flickering" you see looks like the titlebar showing through, even though it shouldn't be. I bet when we hide the titlebar in that PR, this will go away

**Comment by poqdavid** [comment]
@237dmitry No it's not just pwsh I tested it with other ones too and I did a profile reset also, I repaired the app but didn't make any difference I even tested different rendering options with the preview version

> This just looks like a bug with acrylic itself. Can you file feedback via the Feedback Hub? I don't know what the area path for that might be... maybe Composition? Effects? Not sure if those are real paths.
> 
> I suspect this might get better with #13935. The "flickering" you see looks like the titlebar showing through, even though it shouldn't be. I bet when we hide the titlebar in that PR, this will go away

@zadjii-msft Oh sure here just made the feedback https://aka.ms/AAiq4zx, and also is there any ETA on when that PR will be on the preview version?

**Comment by lhecker** [comment]
This issue seems quite unusual. I don't think we've seen anything like this before (with something like that green flickering), right? I hope your main memory / RAM isn't defective...

**Comment by poqdavid** [comment]
> This issue seems quite unusual. I don't think we've seen anything like this before (with something like that green flickering), right? I hope your main memory / RAM isn't defective...

oh sorry I should have mentioned that green color is just my theme color I keep changing it to different ones time to time

**Comment by zadjii-msft** [comment]
also relevant: 

* #13200 
  - this was promoted to MSFT:39958690, which is fixed, but unfortunately doesn't have a link to the commit, so I can't be sure which build that's in. Something >22621, that's for sure.

**Comment by poqdavid** [comment]
@zadjii-msft should I change my feedback from `Category Apps > Windows Terminal` to something else?

**Comment by zadjii-msft** [comment]
Hey just looping back on this, lost it over the holidays. 

"Category Apps > Windows Terminal" probably won't get this to the right area path. That would go to us, but our feedback provider isn't gonna capture the graphics traces that {someone} needs. There's probably a more accurate one for a "composition" or "acrylic" area. Alas, Feedback Hub is turbofucked on my machine so I can't look it up myself 😕 

It's also possible that this was something that was already fixed by the composition team. Did this happen to go away on its own/?

**Comment by poqdavid** [comment]
@zadjii-msft Well I just checked both `Windows Terminal Preview
Version: 1.17.1023` and `Windows Terminal
Version: 1.16.10262.0` they still have the same exact problem unfortunately

also what category I should change it to?

**Comment by carlos-zamora** [comment]
> @zadjii-msft Well I just checked both `Windows Terminal Preview Version: 1.17.1023` and `Windows Terminal Version: 1.16.10262.0` they still have the same exact problem unfortunately
> 
> also what category I should change it to?

Try "Desktop Environment" > "DWM (Desktop Window Manager)"

**Comment by poqdavid** [comment]
> Try "Desktop Environment" > "DWM (Desktop Window Manager)"

Ok thank you since I couldn't edit the feedback I made a new one and linked the existing one and here is the new one https://aka.ms/AAjms05

**Comment by DHowett** [comment]
Thanks for the feedback! We're tracking it internally at (you won't be able to see) MSFT-43378906

Marking this one up for "external" tracking.

**Comment by marbaa** [comment]
Stable Version: 1.17.11461.0

I'm not experiencing flickering, but when Acrylic tabs are enabled, when I switch to other tab, the tabbar switches from acrylic to transparent and stays transparent. It doesn't happen when making screenshot or recording screen with Snipping tool.

When I take focus away from Terminal and bring back, tab bar is acrylic again. Then switch to other tab and it is again transparent.

Dell 7560 with Nvidia T1200 GPU.

**Comment by poqdavid** [comment]
I still get it on both the Stable and Preview version
Asus GL504GW with Nvidia 2070 (TU106M) driver 537.34


> Stable Version: 1.17.11461.0 Windows 11 22621.2134
> 
> I'm not experiencing flickering, but when Acrylic tabs are enabled, when I switch to other tab, the tabbar switches from acrylic to transparent and stays transparent. It doesn't happen when making screenshot or recording screen with Snipping tool.
> 
> When I take focus away from Terminal and bring back, tab bar is acrylic again. Then switch to other tab and it is again transparent.
> 
> Dell 7560 with Nvidia T1200 GPU.

Are you using Gaming or Studio drivers?
I am not sure with professional mobile graphics cards what driver is mainly used I assume it would be the Studio version

**Comment by marbaa** [comment]
No idea which are those. Notebook is managed by our IT department.
Current version: 528.79

![image](https://github.com/microsoft/terminal/assets/40859847/81823a87-ce61-4347-a0a4-eb27b936f43b)

**Comment by krali27** [comment]
I've been seeing this flickering for a while on my Asus Flow X16 (2023 model). Has both an Intel XE igpu (Which is what I use for anything desktop) and Nvidia 4070 mobile, using Studio drivers.  It usually happens whenever I use Terminal but not always, and sometimes goes away or gets better.

Intel driver version is 31.0.101.4575 (latest offered by Asus)
Nvidia driver is 536.67 / 31.0.15.3667 (not up to date, but I'm not using dgpu much and not for this)

**Comment by zadjii-msft** [comment]
note to self: I actually _don't_ think that this is related to #16745

**Comment by marbaa** [comment]
Seems this is another, unsolvable issue. Tab bar randomly flickers on new tab, window losing focus, etc.
Doesn't matter if I set Intel iGPU/Nvidia dedicated/Let Windows Decide for GPU acceleration in Windows settings, or completely disable hardware acceleration in Terminal.

I would rather remove/not ship feature that doesnt' work and is impossible to fix for 2+ years.

Stable: 1.22.3231.0
Preview: 1.22.3232.0
Canary: 1.23.3411.0

**Comment by Elkeid-me** [comment]
Same issue, but only when I am using Windows 11. Windows 10 doesn't seem to have this issue.

I didn't conduct further research. Perhaps it's just the well-known decline in code quality of Windows 11.

**Comment by cmdshft** [comment]
Also having this issue. Please update us.

https://github.com/user-attachments/assets/b7c36118-6a45-40a4-9335-e18bb92c2e88

**Comment by BoscoDomingo** [comment]
Can confirm this started happening out of nowhere a few weeks back. I see the same thing as @cmdshft, although now it only happens on startup. If you change focus to another program and back to Terminal, it stabilises

**Comment by kamronbatman** [comment]
This started happening for me too after the last update (v1.22.12111.0). Using Powershell 7.5.2 in case that matters (shouldn't).

**Comment by cmdshft** [comment]
This is still an issue almost 4 years later, what gives?

Today I am still having this issue. I have noticed that it flickers on the displays that have a lower framerate compared to my primary desktop display, which has a higher fps and doesn't flicker.

https://github.com/user-attachments/assets/594323a8-c131-47c3-a83e-102434c940eb

**Comment by niiiksh** [comment]
I moved to Linux Ubuntu because of this bug

**Comment by qvattr0** [comment]
I've started having this issue as well. I'm somewhat certain that it has something to do with animated backgrounds because whenever I pause my animated background in Wallpaper Engine, the flickering no longer happens.

**Comment by qvattr0** [comment]
A side-question for those who may have more knowledge in this domain: when one uses Mica, does Terminal default to using it instead of some internal engine for calculating the blur effect? I'm currently trying to figure out why I was not having this issue in the past despite using animated backgrounds. I've only started having this issue after a clean reinstall of Windows (11 Pro) and one of the things that did change in my configuration (I'm sure there were many things that changed, making this hypothesis fairly weak) is me stopping the usage of Mica.

**Comment by Stanzilla** [comment]
https://github.com/user-attachments/assets/6680e5d9-1dc7-48e3-a369-f6c3d462aa78

still an issue today. 

Version: 1.24.2812.0

**Comment by cmdshft** [comment]
> I've started having this issue as well. I'm somewhat certain that it has something to do with animated backgrounds because whenever I pause my animated background in Wallpaper Engine, the flickering no longer happens.

I just tested this by shutting off Wallpaper Engine entirely, and I had a Discord window open underneath and it seems that it still glitches if you cause any animated effects in any windows.

**Comment by kariudo** [comment]
This has been going on for me for ages, at one point I thought it was due to my use of Lively; however, stopping that doesn't stop it, just makes it less frequent, as others have noticed, it seems animation/video playback in other windows on other monitors can seemingly cause it. 

My only real solution was disabling the acrylic for the toolbar:

<img width="1025" height="281" alt="Image" src="https://github.com/user-attachments/assets/1d8eb63a-d916-45c4-85a4-1bfdc111c874" />

**Comment by nothinglastsforever** [comment]
> > I've started having this issue as well. I'm somewhat certain that it has something to do with animated backgrounds because whenever I pause my animated background in Wallpaper Engine, the flickering no longer happens.

> I just tested this by shutting off Wallpaper Engine entirely, and I had a Discord window open underneath and it seems that it still glitches if you cause any animated effects in any windows.

I've tried running without either WE or Discord and had no success. The issue persists.

**Comment by pcgeek86** [comment]
I'm still having this problem on fully updated Windows 11.

Windows Terminal 1.23.13503.0
NVIDIA GeForce RTX 4070 Ti SUPER
NVIDIA driver 591.59

**Comment by BoscoDomingo** [comment]
After it had gone away, it's come back for me today

https://github.com/user-attachments/assets/850c498c-565e-40d0-a28f-6da555a0b762

**Comment by atombun** [comment]
the fact that this is still a persistent problem is quite concerning...

**Comment by cmdshft** [comment]
> the fact that this is still a persistent problem is quite concerning...

I agree. I know this is mainly a visual bug, but I wish it had a sense of priority in fixing because it's extremely distracting when you're doing long terminal work.

**Comment by zadjii-msft** [comment]
Great thing that there's a PR for this 😉 #19705

We just need someone who can actually repro this behavior to help validate that this PR does in fact, fix the issue.

**Comment by cmdshft** [comment]
> Great thing that there's a PR for this 😉 [#19705](https://github.com/microsoft/terminal/pull/19705)
> 
> We just need someone who can actually repro this behavior to help validate that this PR does in fact, fix the issue.

There's a bunch of videos posted showing this bug. I've posted one myself. Feel free to send me a build with the fix pulled in to test, I can report back later today if it's fixed or not.

**Comment by pcgeek86** [comment]
I'm still consistently having this problem to this day. Feel free to send me a new build and I can validate the fix as well.

**Comment by TReKiE** [comment]
I compiled and ran the PR'd version and didn't have much luck, the flicker remains for me.

https://github.com/user-attachments/assets/6a7e1d13-3771-4054-a574-a6f2e4608f4a

On both this PR and the current release, if I set the background opacity to be 100%, the problem disappears and returns if I set it <100%.

https://github.com/user-attachments/assets/9b8a0f93-f3f5-4dc6-b3ab-dbd2bee6c5e9

Here are some possible repo steps, although this is highly configuration specific, I can't reproduce the problem on my laptop.
1. Open Terminal.
2. Open Settings, Appearance, enable 'Use acrylic material in the tab row'.
3. Still in Settings, choose the profile you're testing, choose Appearance, scroll down to Transparency and set Background opacity to less than 100% (i.e. 99%), and enable 'Enable acrylic material'.
4. Choose the Save button at the bottom.
5. Open new tabs in the terminal, go through Settings, bring focus to another application, wait a few seconds and then bring focus back to the terminal window etc., observe the flicker in the tab bar.
6. If flicker is not appearing, move the terminal window so that the tab bar appears immediately on top of a File Explorer window's address bar/breadcrumb and repeat.  (See example videos above.)

Not that it isn't noticeable, but I can see the flicker appears worse in the videos above.  I don't have one to test, but I would suspect the problem might be even less noticeable if one is using a higher refresh rate screen.

Also, I think the problem might get worse the longer the Terminal remains open/in use.  Initially it seems fairly tolerable, just a little flicker when switching around, but inevitably it flickers as you type, output scrolls up, etc.  I've had the acrylic tab bar off for a long time because the flicker was too distracting so this may or may not still be the case.

Finally, the problem occurs in both Dark and Light modes.

**Comment by johanneshardt** [comment]
Can confirm, i tried out the fix in the PR as well, it did not help. Interesting that the issue seems to be linked to, as @TReKiE said, having 1. acrylic enabled for the background as well, and 2. having an opacity below 100%. For me, the most annoying thing is when i have some animated content beneath the terminal window,i still get exactly the same behavior as in https://github.com/microsoft/terminal/issues/18791. I would show a screencap as well, but somehow, recording with "snipping tool" fixes the flickering 😅

**Comment by robross0606** [comment]
I was not seeing this at all on Windows 10, but the second I updated to Windows 11 I noticed it immediately.  All sorts of strange flickering and visual artifacts in the title bar area.  It is very distracting.

**Comment by marbaa** [comment]
> Great thing that there's a PR for this 😉 [#19705](https://github.com/microsoft/terminal/pull/19705)
> 
> We just need someone who can actually repro this behavior to help validate that this PR does in fact, fix the issue.

Repro is simple. Any version of Windows 11, default Terminal installation -> Enable tab acrylic.
Doesn't matter if Nvidia GPU, or Intel GPU. I don't have AMD to confirm.

**Comment by xmexg** [comment]
This might actually be a hardware issue. I own an asus-tuf-gaming-f16-2024, and before May 20, 2026, I had the exact same problem described in this thread. After May 20, 2026, ASUS support replaced the entire motherboard for free under warranty.
I did not replace the RAM or SSD, and I didn’t modify the operating system in any way. What’s interesting is that the exact same system setup would flicker randomly before May 20, 2026, but after the motherboard replacement on May 20, 2026, the issue completely disappeared.


这或许是硬件问题，我的笔记本电脑华硕天选5pro，在2026年5月20日前和帖子一模一样，2026年5月20日之后，售后免费给我更换了一整套主板。我没有更换内存条和硬盘，也没有修改系统，奇妙的是，相同的系统，在2026年5月20日之前会flickering randomly，在2026年5月20日之后完全正常。

**Comment by TitaniumX9000** [comment]
> I would show a screencap as well, but somehow, recording with "snipping tool" fixes the flickering 😅

> This might actually be a hardware issue. I own an asus-tuf-gaming-f16-2024
> 笔记本电脑华硕天选5pro

我也是同款天选的原装版本. 感觉和硬件有一定关系但不大, 更可能是像Acrylic的底层渲染管线到显存这中间某些环节的问题, , 用OBS调用Windows自带的录屏录下的视频里面没有这个闪烁的效果. 而且不是帧率和刷新率导致的, 因为不管屏幕刷新率设置多少都录不下来. 视觉上却可以很明显地看出来, 但视频完全看不到. 而且我最开始是异常闪烁, 后来测着测着干脆变成异常的不透明像素区域了. 闪烁/异常渲染区块大多数时候只出现在鼠标位于tab bar上方的时候才出现, 鼠标移动会导致异常渲染区块随之刷新, 有时候就像刷子刷掉污垢一样.

Still experiencing this issue today, regardless of which GPU is active or the refresh rate configuration. 

Initially, it was just random high-frequency flickering between transparency and arylic effects, but it has since escalated into persistent opaque pixel glitching. These graphical glitches only show up when my cursor hovers directly over the tab bar, especially after its hovering around the minimize/maximize/close buttons. Interestingly, the glitched areas refresh and change patterns as I move the mouse—sometimes like a "brush" repainting the opaque pixels into acrylic pixels.

I attempted to record this behavior using both the Snipping Tool and OBS (which likely share the same Windows capture interface), but **the resulting video shows no flickering or glitches at all**, completely contradicting what I see on my monitor.

**Disabling MPO does not work either.**

https://github.com/user-attachments/assets/72bc4cfb-cec9-47f4-b331-c662b0bb37fd

https://github.com/user-attachments/assets/f9b59f1c-1963-42e4-8501-27c358e39295

https://github.com/user-attachments/assets/fdce76b1-c2c3-4a08-bd47-222cf963aab8

_Note: the problem still exists when Wallpaper Engine has been terminated._


**I strongly suspect this is a lower-level composition or VRAM pipeline issue rooted in the Acrylic implementation itself, rather than a specific hardware driver bug. Since the flickering/glitch persists identically regardless of whether the iGPU or the dGPU is active, it points away from device-specific rendering and more towards how DWM or the terminal's composition layer handles alpha-blending and mouse hover redrawing.**


```
Windows Terminal 1.24.11321.0
Windows Insider Preview Build 26300.8497
```

**Comment by robross0606** [comment]
It does seem to be related to either device or driver.  I have a laptop with fairly typical Intel/Nvidia combo.  When using the default Intel video, it flickers like mad.  I went into the display settings and told it to use my Nvidia chip for the terminal app and no more flicker.

**Comment by Chris123NT** [comment]
Nearly 4 years later and this is still bugged. Is there any reason why the proposed PR's to fix this haven't seen any real consideration? I mean, it seems like a pretty obvious thing that needs fixing, damn thing flickers like crazy every time I switch focus on my PC.

Might just get my build environment going to compile terminal with the fix and verify that it indeed takes care of the issue.

**Comment by niiiksh** [comment]
> Nearly 4 years later and this is still bugged. Is there any reason why the proposed PR's to fix this haven't seen any real consideration? I mean, it seems like a pretty obvious thing that needs fixing, damn thing flickers like crazy every time I switch focus on my PC.
> 
> Might just get my build environment going to compile terminal with the fix and verify that it indeed takes care of the issue.

This was the last reason I left Windows for Linux Ubuntu.

**Comment by Chris123NT** [comment]
> Nearly 4 years later and this is still bugged. Is there any reason why the proposed PR's to fix this haven't seen any real consideration? I mean, it seems like a pretty obvious thing that needs fixing, damn thing flickers like crazy every time I switch focus on my PC.
> 
> Might just get my build environment going to compile terminal with the fix and verify that it indeed takes care of the issue.

Just to come back to this, pulled the source tree into VS and added the PR as seen here: https://github.com/microsoft/terminal/pull/20316

I can confirm this FIXES the issue. My self compiled instance of terminal doesn't flicker at all now. Would be nice if this could be merged, although if I have to maintain my own instance of Terminal canary for now I guess that's okay :)

**Comment by cmdshft** [comment]
Can we please get this fix pushed asap???

**Comment by romanlex** [comment]
can confirm issue!

**Comment by iccfish** [comment]
I cann't believe that this issue has been 4 years ..
