### ISSUE TITLE
cursor disappears after some time

### ISSUE THREAD

**Issue by mypalabok** [microsoft/terminal#158]
* Your Windows build number:  Microsoft Windows [Version 10.0.16299.371]

* What you're doing and what's happening: just using the console, doing some admin stuff then after some time i notice that the cursor can't be seen although i can still type/edit

* What's wrong / what should be happening instead: cursor disappears. if i restart the WSL box then cursor reappears.

**Comment by zadjii-msft** [comment]
I can't really do anything with this bug report. I'm going to need some sort of repro steps to be able to investigate. Is there any program you're using that you notice the behavior in specifically?

**Comment by mypalabok** [comment]
i am just in the bash shell doing editing of files. the effect is random but it always happens.

**Comment by mypalabok** [comment]
hi. i finally narrowed it down and it has to do with the mail client "mutt". should i post it here or goto mutt forum?

**Comment by parkovski** [comment]
I’m not sure if this is the same issue, but I’ve noticed my cursor jumping to the bottom right corner of the screen sometimes, though it comes back when I start typing. Could be a combination of that plus mutt caching the cursor position and just issuing move by offset rather than full position escapes, just a guess. I’ll try to get a good repro a little later.

**Comment by davidanderle** [comment]
I have a similar issue to @mypalabok, though the cursor does not recover even after hard resetting my computer. When this happened last time, I was able to update my windows to a fast ring insider preview, which resolved the issue... Or I thought until today, when the cursor had disappeared from CMD, PowerShell, and from WLS while I was editing a file in vim. I cannot recreate the problem, since I cannot recover its normal function. All my terminals on my Windows became unusable for text editing. Any ideas what I could try to get the cursor back?

**Comment by chris-sparks** [comment]
FWIW I too am facing a similar issue to the OP.

The cursor blinks fine when 'idle' but as soon as you 'wake it up' it disappears and does so until x time has lapsed, at which point it returns to visible. Obviously navigating back with the arrow keys is rather difficult as there's no indication of where the cursor is located.

Occurs on the shell as well as in, say, nano/vi etc.

I have no discernible reason I can find for why and when this started to happen, perhaps a recent update, but when I first noticed it I made an assumption it was just a one off and a restart would cure it. That's not the case.

GIF attached.

![cursor-woes](https://user-images.githubusercontent.com/19639926/47540234-8f432500-d930-11e8-9c16-af4526f9f410.gif)

**Comment by zadjii-msft** [comment]
@chris-sparks That's definitely #269, which is fixed in the newest insider's builds. 

@mypalabok is that the issue you were seeing? If so, I'd love to close this issue as a dupe.

**Comment by miniksa** [comment]
Looks like this is fixed/answered. Closing.

**Comment by mloskot** [comment]
@mypalabok Did you have a chance to test the problem in other terminals?

I'm seeing the disappearing cursor while editing e-mails in Mutt + Vim under WSL, saving a draft, re-opening and the cursor is gone. I have to quit Mutt, execute `reset` and re-launch Mutt, then cursor is back.

I'm now trying out the `Windows Terminal (Preview) Version: 0.3.2171.0` with WSL (Ubuntu 18.04) and Mutt, so far so good, cursor does not disappear.

**Comment by hi2u** [comment]
This is a regular occurrence for me and always has been since I started using Windows Terminal earlier in the year.

It seems to happen both for local cmd.exe prompts, and also when logged into remote Linux hosts over SSH.  I'm guessing it's related to ANSI escape/color codes or something like that.     

I do a fair bit on Node.js programming, and it seems to be pretty common after running a Node.js program that uses ANSI escape color codes.

For the remote Linux shells over SSH, I can fix it by running the `/usr/bin/reset` command.

It probably happens at least 10 times a day for me.  I find myself having to either run `reset` or close and reopen terminals quite a lot.

I thought maybe `htop` was one of the causes, but trying it now I can't replicate the issue consistently.  But given that it also happens in cmd.exe, it seems it's not one specific Windows -or- Linux cause or program.

Running the current version: 1.0.1401.0

**Comment by robinZhao** [comment]
The problem remains in 10.0.18363.1016
![](https://raw.githubusercontent.com/robinZhao/images/master/issue.gif)
