### ISSUE TITLE
Broken display of some characters.

### ISSUE THREAD

**Issue by fr0zert** [microsoft/terminal#16757]
### Windows Terminal version

1.19.240130002

### Windows build number

10.0.19044.0

### Steps to reproduce

I use a custom prompt [starship](https://starship.rs) with default preset called [Tokyo Night](https://starship.rs/presets/tokyo-night.html), with [nerdfont](https://www.nerdfonts.com) called FiraCode(Mono)
![image](https://github.com/microsoft/terminal/assets/52128237/e30ac1b8-ecf3-49af-b3e9-f4b9c5535ed6)

### Actual Behavior

Custom prompt uses the semicircle symbol ""(\ue0b4) at the start of which, at certain zoom values(font size 11 for me), an extra pixel appears.
![image](https://github.com/microsoft/terminal/assets/52128237/17967503-db64-4906-9aca-3a330f502eb3)

The problem appeared with the latest updates, since I have two versions of the terminal on the device, I can run them in parallel using all the same settings, and in the old version of such a problem is not observed.

![image](https://github.com/microsoft/terminal/assets/52128237/5d2925e1-a887-440f-b81f-12233a0d07d0)

**Comment by lhecker** [comment]
Thanks for the feedback! This was recently fixed by #16729 which will ship in the next Windows Terminal version. We're still working on the fine details, but powerline glyphs will work for sure.

**Comment by fr0zert** [comment]
@lhecker ah it's been like two or three updates, and the problem's still there, even tried the pre-release version, it has this problem too. What's interesting is that when you answered me, I decided to try the pre-release version and it was already fixed there, but it looks like the problem is back (even though it never disappeared on release)

**Comment by lhecker** [comment]
When you say "pre-release version" are you referring to the preview version? #16729 wasn't released in preview yet. You need to use our nightly builds ("canary") instead. You can find the download links here: https://github.com/microsoft/terminal/discussions/16121
(I recommend the App Installer.)

**Comment by fr0zert** [comment]
oops, I apologize, I did get the url mixed up and was checking the wrong build 😬
