### ISSUE TITLE
Binding 'paste' to shift+insert doesn't work

### ISSUE THREAD

**Issue by easeev** [microsoft/terminal#1787]
# Environment

```none
Windows build number: 10.0.18922.1000
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

Add the following to the `keybindings` section of `profiles.json`:

```
{
	"command" : "paste",
	"keys" : 
	[
		"shift+insert"
	]
},
```

# Expected behavior

Text is pasted once I press Shift+Insert. I'm on WSL terminal.

# Actual behavior

Nothing happens. If the binding is disabled, I get `2~` when this key combination is pressed.

Reference: https://github.com/microsoft/terminal/issues/112#issuecomment-507822964

**Comment by bronthulke** [comment]
I've also tried to bind "paste" to ctrl+v and that didn't work either - perhaps is the "paste" keybinding command not set up to work at all?

**Comment by DHowett-MSFT** [comment]
Not in 0.2.1715.0!

**Comment by DHowett-MSFT** [comment]
#1093

**Comment by easeev** [comment]
Looking forward for Microsoft Store update!

**Comment by sandric** [comment]
Hmm, mine version is 0.2.1831.0, and I still have no luck making such shortcut working, should this work?

**Comment by DHowett-MSFT** [comment]
Not in 0.2.1831.0.

**Comment by bronthulke** [comment]
I think there's some confusion here @DHowett-MSFT - when you simply say "Not in 0.2.1715.0!" do you mean that it's no longer an issue in 0.2.1715.0?  As that is what I thought, and it implies that it would also be fixed in 0.2.1831.0 as @sandric is experiencing.  A few extra words may assist in our understanding :)

**Comment by DHowett-MSFT** [comment]
Hey, sorry! These key bindings didn’t make it into the 0.2 release (neither the original release nor the servicing release). It will come out with the 0.3 preview release. Thanks!

**Comment by bronthulke** [comment]
Awesome, thanks for clarifying!

**Comment by tovine** [comment]
This still doesn't work for me... Except for in PowerShell, for some reason.
In all other terminals it just outputs `~2` (bash) or nothing at all (CMD)...
I have tried:
- Cygwin
- CMD
- Debian in WSL

I'm running Windows Terminal (Preview)
Version: 0.6.2951.0
Windows 10 Enterprise, Version 10.0.18362 Build 18362

This is from my keybindings config (oh, and `ctrl+shift+v` works so the config seems to be correct):
```
    "keybindings": [
        {
            "command" : "paste",
            "keys" :
            [
                "shift+insert",
                "ctrl+shift+v"
            ]
        },
        {
            "command" : "copy",
            "keys" :
            [
                "ctrl+insert",
                "ctrl+shift+c"
            ]
        }
    ]
```

**Comment by DHowett-MSFT** [comment]
Sorry -- this is a doc fail for us. `keys` is for _chording_ (where you must press all the keys in the list, in order). You'll want to just add another `{"command":... "keys"...}` instance to bind the `inserts`

**Comment by tovine** [comment]
You're right, thanks a lot for the tip! 😄

**Comment by evolite** [comment]
> Sorry -- this is a doc fail for us. `keys` is for _chording_ (where you must press all the keys in the list, in order). You'll want to just add another `{"command":... "keys"...}` instance to bind the `inserts`

Can you specify how the configuration should look in order to make shift-insert paste work?
