### ISSUE TITLE
terminal is always hang

### ISSUE THREAD

**Issue by heartacker** [microsoft/terminal#18353]
### Other Software

![Image](https://github.com/user-attachments/assets/52c19258-2691-46c5-82c6-638ec95f6aec)

### Steps to reproduce

launch and hang

### Actual Behavior

bug

**Comment by viceice** [comment]
Seeing it too. terminal tab hungs after typing some chars. Will continue to work after some seconds to minutes.
![Image](https://github.com/user-attachments/assets/4393a777-6d2e-4f37-96c5-953885631014)

**Comment by viceice** [comment]
Same happens for preview `1.22.3232.0` installed via store.

Terminal windows is usable and you can still open new tabs or change settings.
But after typing a few characters to a console it hangs for a while and doesn't accept any futher input.
It's happening on cmd / pwsh and wsl. Probably also on the other shells too.

**Comment by carlos-zamora** [comment]
Thanks for filing! Can one of you capture a dump and share it with us /? Instructions here: https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capturing-and-sending-dumps

**Comment by zadjii-msft** [comment]
Idle thought: I think this is fixed in #18248

Can you try [Installing Terminal Canary](https://github.com/microsoft/terminal#installing-windows-terminal-canary)?

**Comment by NekoCompiler** [comment]
![Image](https://github.com/user-attachments/assets/b9383526-d397-4dfc-b0fb-9dbbf0bb29a9)
The issue is 100% reproducible in the illustrated version.

**Comment by xchgeaxeax** [comment]
> Idle thought: I think this is fixed in [#18248](https://github.com/microsoft/terminal/pull/18248)
> 
> Can you try [Installing Terminal Canary](https://github.com/microsoft/terminal#installing-windows-terminal-canary)?

This problem is fixed in the canary version.
![Image](https://github.com/user-attachments/assets/95702c7e-5511-4b4f-8289-34a1a6f9e3a3)

**Comment by heartacker** [comment]
Looking forward to releasing a new version soon.

**Comment by DHowett** [comment]
I'll mark that one up for backporting. Thanks!

**Comment by viceice** [comment]
Here's a minimal dump https://1drv.ms/u/c/d68416fa9dc606f2/EZRnpmdAMrdElCFdENqdZt0Bn2i-cdw-9aS2pjZNT1oeHA?e=ZxkzOj

**Comment by viceice** [comment]
For me the bug still exists in canary v1.23.10081.0
minimal dump: https://1drv.ms/u/c/d68416fa9dc606f2/EWv8fQGl7h5IpYmFG453hvcBlqxKbHTeSgVwUENIJBrYgw?e=zI96VH

**Comment by viceice** [comment]
Anything else i can provide? Terminal isn't usable in this state and i need to use Tabby or similar alternate

**Comment by viceice** [comment]
it seems after installing jan 2025 updates and a reboot it works as expected again 🤔

**Comment by carlos-zamora** [comment]
Thanks for following up! Closing

**Comment by heartacker** [comment]
> jan 2025 updates

@viceice hi， what is this？ is this a terminal update or windows update?

why i can not find this?

@zadjii-msft hi,is there an update for terminal stable, thanks

**Comment by viceice** [comment]
windows update. I think the reboot fixed it somehow. 🤷‍♂️

 I usually doing hibernate for a month until windows updates need to reboot the system.

**Comment by NekoCompiler** [comment]
No fix at all. Why is this issue closed.

![Image](https://github.com/user-attachments/assets/7011a661-8a14-462a-853a-f7b10966a8ab)

![Image](https://github.com/user-attachments/assets/f927190a-8ae7-4e05-b8c6-73e7353dfecc)

![Image](https://github.com/user-attachments/assets/470fd8e0-16fd-4009-8ba0-3b69ce70b4fb)

**Comment by NekoCompiler** [comment]
It's crazy that a fatal problem with a terminal software has not been fixed since it went wrong last October until now.

**Comment by NekoCompiler** [comment]
Nothing fixed. Happy 5th month for this fatal bug!

![Image](https://github.com/user-attachments/assets/04a27767-f84e-4266-948c-db250367f441)

**Comment by lhecker** [comment]
> Hypothetically, if this were the same issue with GNOME Terminal or Konsole, I wonder how much flak those two programs would get.

Don't worry, we get dozens of comments per day just in this repository. A good chunk of them are flak.

> Nothing fixed. Happy 5th month for this fatal bug!

If the issue happens again, please capture a heap dump and open a new issue: https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capture-with-task-manager

We have also rewritten the windowing implementation for Windows Terminal Preview 1.23 in order to fix issues like this one. You can download it here: https://github.com/microsoft/terminal/releases/download/v1.23.10353.0/Microsoft.WindowsTerminalPreview_1.23.10353.0_8wekyb3d8bbwe.msixbundle

(Note, however, that this is the first Preview version for 1.23 and as such has several bugs that we still need to fix. We're hoping to release the first bug fix release soon.)

**Comment by LordHumphrey** [comment]
same problem here, happens on one of my pc+1

**Comment by heartacker** [comment]
this issue is not FIXED

Please reopen this


I Update the latest version , IT hangs again and again

![Image](https://github.com/user-attachments/assets/4c285ffc-df07-43ea-96ea-f58e7e196ac1)

**Comment by lhecker** [comment]
Sure! As I mentioned last month, a heap dump is required: https://github.com/microsoft/terminal/issues/18353#issuecomment-2680146247
Please make sure to use Windows Terminal Canary.
