### ISSUE TITLE
MSYS2 bash: Cursor display doesn't follow arrow keys after running Emacs

### ISSUE THREAD

**Issue by andreaszapf** [microsoft/terminal#2697]
# Environment

```none
Windows build number: [10.0.18362.295]
Windows Terminal version (if applicable): 0.4.2382.0

Any other software?

MSYS2 / MINGW64:

  $ uname -srvo
  MINGW64_NT-10.0-18362 3.0.7-338.x86_64 2019-07-11 10:58 UTC Msys

  $ bash --version
  GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

Emacs from MSYS2's mingw64/mingw-w64-x86_64-emacs package:

  (emacs-version)
  "GNU Emacs 26.2 (build 1, x86_64-w64-mingw32)
   of 2019-06-03"

```

# Steps to reproduce

- Run MSYS2 / MINGW64 bash in Windows Terminal, e.g. in a CMD tab with
  `set MSYSTEM=MINGW64&& c:\msys64\usr\bin\bash --login -i`

- Run Emacs in the terminal (`emacs -nw`) and quit it immediately

- Back at the bash prompt, enter a few characters, say `123`

- Press the left-arrow as often as needed to move the cursor to the 
  beginning of the line (in this example 3 times)

- Enter some other characters

# Expected behavior

- The cursor moves with the left-arrow keystrokes to the beginning of the line

- New text appears line start

# Actual behavior

- The cursor stays at the end of the line, although the internal position is updated
  and new text appears at line start. 

- When I delete text using Backspace or Delete, the cursor jumps to the correct position, 
  but jumps back to the end of line when new text is entered.
  
It seems that MINGW Emacs and MSYS2 bash don't play well in Windows Terminal -- in
the classic Windows console there is no issue.

This might be related to #2561.

**Comment by zadjii-msft** [comment]
@andreaszapf Does this repro in emacs in WSL for you as well, or only the MSYS2 emacs?

**Comment by andreaszapf** [comment]
@zadjii-msft Emacs in WSL works fine for me. That is, Emacs 25.3.1 on an older WSL (let me know if you need the exact version).

**Comment by zadjii-msft** [comment]
Good to know - that means it's specific to the Terminal's VT processing, and not a broader issue with conpty. Thanks for confirming!

**Comment by zadjii-msft** [comment]
@andreaszapf I know that this a long shot, but is this still repro'ing for you? I just tried installing the 20190524 MSYS2 build locally, and this doesn't seem to repro on the 0.8.10091.0 build of the Windows Terminal anymore. I thought I had a fix in #4372 for this, but since it's not even occurring in 0.8, then maybe it was fixed by something else earlier.

**Comment by andreaszapf** [comment]
@zadjii-msft It's still reproducing for me, I just checked with a fresh MSYS2 install like the one you used (msys2-x86_64-20190524).

Here is what I did step-by-step, after installing MSYS2, in a CMD tab in Terminal:
```shell
C:\>set MSYSTEM=MINGW64&& c:\msys64\usr\bin\bash --login -i
$ pacman -S -q --noconfirm mingw64/mingw-w64-x86_64-emacs
$ emacs -nw --eval '(save-buffers-kill-terminal)' # open and immediately close emacs
$ abcde
# cursor can't be moved with arrow keys...
```

**Comment by zadjii-msft** [comment]
Well that's no good. Doing the exact same thing _works fine on my machine_<sup>tm</sup>
![image](https://user-images.githubusercontent.com/18356694/73405813-86bb6600-42ba-11ea-9276-360e56e00cfd.png)


Maybe this will just go away in the next version with #4372 🤞

**Comment by andreaszapf** [comment]
> Maybe this will just go away in the next version with #4372 🤞

Seems like it does :grin: -- I finally got around to building Terminal from source (which worked flawlessly :clap:), and I'm seeing the issue on `master` but not on the #4372 branch. 

Looking forward to the next release!

**Comment by zadjii-msft** [comment]
Oh that's great to hear! I'll tag this up appropriately then. Thanks for taking the time to build this and confirm!

**Comment by DHowett-MSFT** [comment]
I'm .. actually unfortunately still seeing this with 0.9.301.0, which does contain #4372. It trivially reproduces if I hide the cursor and then try to move around my prompt line as well. :/

**Comment by DHowett-MSFT** [comment]
Oh, I see. I'm using `25l` instead of `12l`. _Interesting._ WT should be hiding the cursor on 25l. Okay. This is just a different issue. :smile:
