### ISSUE TITLE
"The parameter is incorrect" on First Run

### ISSUE THREAD

**Issue by Blizzardo1** [microsoft/terminal#4095]
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.7.3451.0

Any other software? Not that I can think of to cause this application to crash.
```

# Steps to reproduce

Install from Microsoft Store or download from Releases Tab.
Open Program

# Expected behavior

First Run default profile loaded for configuring

# Actual behavior

Upon opening program, the following error happens:

[C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.7.3451.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe]

C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.7.3451.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

The parameter is incorrect.

This doesn't happen on my laptop which is weird. Other UWP(style) programs do run like the Camera App, Calculator, etc. It's just this particular program that doesn't like my copy of Windows.

**Comment by zadjii-msft** [comment]
@Blizzardo1 Any chance you're using the UTF-8 system code page?
> ![image](https://user-images.githubusercontent.com/18356694/71671916-f7ae4300-2d39-11ea-8312-95e6b4ac7aea.png)

The symptoms sound similar to #3039

**Comment by Blizzardo1** [comment]
![image](https://user-images.githubusercontent.com/2950215/71713517-e1969600-2dbe-11ea-9599-13d34547a0bb.png)
It appears that I am not using that option.

**Comment by zadjii-msft** [comment]
Yikes, that's not what I was hoping for. @Blizzardo1 Could you try repro'ing this with the Feedback hub? That'll give us more detailed diagnostics (hopefully). 

/feedback

**Comment by Blizzardo1** [comment]
I had submitted a feedback request yesterday. Hopefully it landed safely :)

**Comment by DHowett-MSFT** [comment]
Would you mind sharing a link to the feedback item you submitted using this button?

![](https://user-images.githubusercontent.com/18221333/62478649-6de55400-b760-11e9-806e-5aab7e085a9f.png)

**Comment by Blizzardo1** [comment]
https://aka.ms/AA6ysuq

**Comment by sandreenko** [comment]
I have hit that today as well.

**Comment by horazius77** [comment]
same problem here

**Comment by DHowett-MSFT** [comment]
And the both of you are also not using UTF-8 ACP?

**Comment by horazius77** [comment]
System: Windows 10 Enterprise 1903 (Build 18362.592)

Just upgraded Windows Terminal from 0.7.3382.0 to 0.8.10261.0 with chocolatey. Problem still exists.
And yes, I am not using UTF-8 (I have not checked: "Beta: Use Unicode...")

Removing and Reinstalling did not fix the problem. Thanks for looking into it.

**Comment by sandreenko** [comment]
> And the both of you are also not using UTF-8 ACP?

I do not.

**Comment by Blizzardo1** [comment]
After upgrading to 1909, same issue happens, I can try reinstalling it again, however I am unsure how it would solve the issue.

**Comment by rushic24** [comment]
I got the same today, the use utf8 checkbox is not ticked in region settings. 
here is my feedback link   [https://aka.ms/AA86hx1](https://aka.ms/AA86hx1)

**Comment by zhang919** [comment]
I have meet the problem too, and Particularly, then I launch any UWP application that contains win32 content will report this error, but native UWP applications will not. I sincere hope this bug can be fix because I cant boot so much useful apps.  Thinks for your attention.
Best.
Zhang.

**Comment by jkozeal** [comment]
I also have run into this issue.  The problem started after I enabled my Administrator account and switched over to use it.  I wanted to use Terminal, so I installed it from the Store, thinking it would then entitle me to Launch.  It seemed to re-install, and worked fine.  When I use the only other account on my PC, I run into the "The parameter is incorrect" error.  Note: if I switch to my Administrator account, Terminal opens without any error.  I have attempted a number of uninstall/re-install variations between the two accounts, but it seems no matter what I try, my Administrator account can open Terminal, and my User account cannot.

**Comment by rushic24** [comment]
I have only one account that to is Administrator, still it doesn't work.

**Comment by ryanprosser** [comment]
I too have been having this exact issue for months
Many release versions of WindowsTerminal, same error on launch
Tried app repair, reset, uninstall

Win AD joined machine
Domain user, who is member of Administrators group
Beta: Use unicode UTF-8 = NOT checked

Submitted feedback. Link is https://aka.ms/AA8a8hw

**Comment by DHowett** [comment]
Unfortunately, we haven't really been able to reproduce this. Is it still happening for you folks?

**Comment by jkozeal** [comment]
Still happening for me, but doesn't seem to be limited to only Windows Terminal.  I installed Ubuntu 20.04 and get the same issue.  I found one 'solution' which is letting me use Terminal - that being to move the entire install folder out of the original location and into C:\Terminal (any other folder location works, really).

**Comment by zhang919** [comment]
Dear @DHowett ，
This seems to be a system-level problem. According to some information I have collected, its triggering cause is confusing. In some cases, some Intel drivers (such as Intel CAS) and even the DISM toolkit included with the system Will activate this problem.
Best.

**Comment by DHowett** [comment]
Thanks for the info. I unfortunately don't think there's anything we can _do_ about it, but I'll leave you with two points.

1. We're investigating other ways to deploy the terminal that may be less fragile - #1386 
2. As @jkozeal found out, Terminal runs well outside the app package. We're not intending on breaking this, so if you _unzip_ the msixbundle and the architecture-specific msix inside it you'll be able to get a durable (**but not automatically upgrading**) Terminal install.

**Comment by Joseph-See** [comment]
I had this same problem after going through updating WSL1 to WSL2. I had to redo that a couple times as I didn't reboot when I should have but eventually got it upgraded.

After that though this problem occurred and I can't open my newly downloaded Windows Terminal.

I ran "sfc /scannow" which found some corrupt files and fixed them. I could then open Windows Terminal.

However, after closing the terminal I get the same problem and "sfc /scannow" doesn't pick up anything. 

I can run the Ubuntu and Kali apps just fine by clicking on the apps from the start menu. Windows Terminal would be really useful to use right now though.

**Comment by Blizzardo1** [comment]
I reinstalled my workstation and to my amazement this issue no longer exists. I think my old instance had some anomaly with certain app packages, and Terminal was one of them. Funny, yet strange. Through these harsh times, I thank everyone that tried to help anyone who experienced this issue. May the 8-bit Gods carry the 1 to forever return SUCCESS.

**Comment by lino-man** [comment]
Fixed the problem moving terminal installation folder. Just change the directory like say %USERPROFILE%\Terminal folder and Voyla. It looks like a security issue in Program Files\WindowsApps directory. Another behavior is the icon that disappears from a shortcut created in desktop or toolbar. There is no need for running sfc /scannow. Sorry for my poor English. Cheers.

**Comment by LostOnTheLine** [comment]
I have this issue as well.

>@lino-man
It looks like a security issue in Program Files\WindowsApps directory

I looked into this & discovered something strange. For some reason my `C:\Program Files\WindowsApps` folder has a strange Permission issue. I figure this may be the cause of the problem & maybe we could look into this & it might solve the problem...
![Windows Terminal Permission Problem](https://user-images.githubusercontent.com/60684934/190173711-f0e2b72c-7727-4680-80c1-6110cf4fe6c6.jpg)

For me the group `Administrators` had permissions set to only `List folder contents` & `Users` had no checkmarks on anything.
I went into the **`Advanced Security Settings`** & 1st issue was they differed from what was shown in the initial settings. Specifically Users had the permission settings `Read & execute`.

![Windows Terminal Permission Problem Advanced](https://user-images.githubusercontent.com/60684934/190179969-9b4a55b8-bfe5-4022-93bf-455c70660b79.jpg)
I also noted that it said the owner of the folder was my Admin & currently logged in user account, which seems to be not what I would expect it to be. & on another system that isn't having this problem the **Owner** was listed as `TrustedInstaller`. Also there as no specific permission for a specific user.
When I tried changing the Owner to `TrustedInstaller` it couldn't find that name. In Advanced I couldn't find it in the list either. This was the same on the other system where Terminal works without issue, so I think it's just that we cannot assign ownership to `TrustedInstaller` manually.

I'm going to try completely removing the folder, & let the OS recreate it, hopefully with the proper ownership & permissions. I'll post the results here when I finish

**Comment by zadjii-msft** [comment]
> I'm going to try completely removing the folder, & let the OS recreate it, hopefully with the proper ownership & permissions. I'll post the results here when I finish

WATCH OUT! I don't think the OS will recreate that! touching that could be **VERY BAD**

**Comment by LostOnTheLine** [comment]
> WATCH OUT! I don't think the OS will recreate that! touching that could be **VERY BAD**

I'm already listsed as the owner of it, so the worse that could happen is that the OS does nothing, unlikely, & I copy it back, maybe that alone will fix the permission issues.

**Comment by LostOnTheLine** [comment]
Intereswting thing to note. Deleting the directory was not possible but the reason seems very odd. There were 4 font TTF files in the Windows Terminal folder that were said to be in use by the system. Restarting into safe made was still unable to because the same files were still `In use`.
I was able to delete them by using the `Shift - Restart` menu `Troubleshooting` > `Command Prompt` option. then using the rmdir /s to remove it.
After removing it I had the issue of the Windows Store, of course, no longer being able to open.
I'm attempting a Windows Update to see if it fixes this. I had done a manual Check for updates after it updated yesterday & it had none. But now it is installing the update `2022-09 Cumulative Update for Windows 10 Version 21H2 for x64-based Systems (KB5017308)` which I'm fairly certain was installed previously. Here's hoping it will restore the store

**Comment by DHowett** [comment]
> I'm going to try completely removing the folder

These folders have special ACLs on them that aren't properly displayed by the UI or backed up by `icacls`. Deleting this folder or otherwise changing its permissions is unfortunately a one-way ticket to a broken install--even if you put it back where it was.

I lost an entire day trying to "fix" a broken `WindowsApps` directory, and that was with the help of the team who made it the way that it is. It's unfortunate.

**Comment by LostOnTheLine** [comment]
> Deleting this folder or otherwise changing its permissions is unfortunately a one-way ticket to a broken install--even if you put it back where it was

Mine was already permission abnormal. I did notice that on my other system I cannot even open the folder with admin permissions. Putting it back everything except the Store is back, I will do a reset sometime later today or tomorrow & hopefully the Microsoft Store will come back, but as it is it's essentially back to the way it was before so not much has changed. The error it gives me when I try to run the store is about some DLL files not being found, so I'm hopeful that it will load them with a restart since one is in the `Microsoft.NET.Native.Framework.1.7_1.7.27413.0_x64__#####`, `Microsoft.NET.Native.Framework.1.7_1.7.27413.0_x86__#####`, `Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__#####`, & `Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x86__#####` folders so I have 4 copies of it (I don't like that it keeps 2 or more of a bunch of folders with different versions but whatever) & the other is in the `Microsoft.NET.Native.Runtime.1.7_1.7.27422.0_x64__#####`, `Microsoft.NET.Native.Runtime.1.7_1.7.27422.0_x86__######`, `Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__#####`, & `Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x86__#####` folders. So if it doesn't work I think reinstalling the .NET stuff should fix that. I just cannot do a reset yet to test it.

**Comment by LostOnTheLine** [comment]
> I lost an entire day trying to "fix" a broken `WindowsApps` directory, and that was with the help of the team who made it the way that it is. It's unfortunate.

How did you get it fixed?

**Comment by zadjii-msft** [comment]
I vaguely recall this thread: https://github.com/microsoft/terminal/issues/13509#issuecomment-1184870634

**Comment by LostOnTheLine** [comment]
I've had many bad experiences with "In-Place Upgrades" so that's a last-ditch for me, but it's at least something if nothing else works. It sounds like, from that thread, that it's saying that having any sort of altered permissions will cause big problems, but mine were already like that... & I could even install other apps fine, but the terminal & other terminal apps like terminus & one other I tried but I can't remember would install but not start.

**Comment by LostOnTheLine** [comment]
So I was able to get everything back to the way it was before I moved the WindowsApps folder by using the PowerShell install method for the Windows Store App. Unfortunately it didn't work with the folder removed though so I had to manually put it back 1st & the folder still has weird permissions.
`Get-AppxPackage -allusers Microsoft.WindowsStore | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register “$($_.InstallLocation)\AppXManifest.xml”}`

Looking into things it seems like creating a new account may do the same to fix it as an in-place upgrade less destructively.
