### ISSUE TITLE
Issue when running ncdu via SSH in Git Bash

### ISSUE THREAD

**Issue by glen-84** [microsoft/terminal#5167]
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.10.781.0

Any other software?

Git for Windows: 2.26.0
```

# Steps to reproduce

1. Create a profile with the `commandline`: `%PROGRAMFILES%/Git/bin/bash.exe -li`.
2. SSH into a Debian64 machine (I'm using VirtualBox).
3. Run `ncdu`.

# Expected behavior

Proper output/rendering.

# Actual behavior

When I run `where ssh`, there are 2 SSH binaries:

* `C:\Program Files\Git\usr\bin\ssh.exe` (OpenSSH_8.2p1, OpenSSL 1.1.1e  17 Mar 2020)
* `C:\Windows\System32\OpenSSH\ssh.exe` (OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5)

I see different incorrect rendering between each of the 2.

1. Using the first (which is the default), I see rendering similar/the same as #4697 (which was closed without a resolution). See screenshot 1 below.
2. Using the second, the rendering is broken in a different way. See screenshot 2 below.

Why do they differ? What is missing in both cases?

* Inside the VM:
    * TERM: `cygwin`
    * LANG: `en_ZA.UTF-8`
    * LC_ALL: ``

![ncdu1](https://user-images.githubusercontent.com/261509/77849078-451b3e80-71c9-11ea-887e-3a3604a96454.gif)
![ncdu2](https://user-images.githubusercontent.com/261509/77849080-49dff280-71c9-11ea-874c-981ddb63d082.gif)

**Comment by DHowett-MSFT** [comment]
Hey, if you change your git bash commandline to include `-li` (like `bash.exe -li`), does the first rendering issue go away? We realized our guidance here was incorrect, and we updated it with the help of the git-for-windows folks.

For the second issue . . . that looks suspiciously like two things:

1. an off-by-one we definitely fixed in 0.10, so it shouldn't be back
2. `LANG` or `TERM` is set incorrectly; can you confirm the values of those? Thanks!

**Comment by DHowett-MSFT** [comment]
(I saw that you mentioned TERM/LANG for the cygwin case, but not the win32-openssh case :smile:)

Unfortunately, I can't reproduce this with ncdu 1.13 on debian when TERM is set to xterm-256color. If I set `TERM` to cygwin, i get the exact same rendering artifacts ... but that's expected, because Windows Terminal speaks xterm-256color, not cygwin!

**Comment by DHowett-MSFT** [comment]
For what it's worth, I see egregious artifacts when I run it using cygwin SSH to a linux machine, even outside of Windows Terminal;

![image](https://user-images.githubusercontent.com/14316954/78330029-e42c9700-7537-11ea-9cf4-1073f8598700.png)

it looks like they're doing something very, very wrong with VT parsing. Cygwin 3.1+ should fix.

**Comment by glen-84** [comment]
> Hey, if you change your git bash commandline to include -li (like bash.exe -li), does the first rendering issue go away? We realized our guidance here was incorrect, and we updated it with the help of the git-for-windows folks.

I'm already including `-li` (it's mentioned under `Steps to reproduce`). 🙂

> (I saw that you mentioned TERM/LANG for the cygwin case, but not the win32-openssh case 😄)

I did so because the values are the same inside the VM, regardless of which SSH binary is used.

On the host, using Git Bash, the values are similar:

* TERM: `cygwin`
* LANG: `en_US.UTF-8` (note: `US` not `ZA`)
* LC_ALL: ``

When I run `TERM=xterm-256color "C:\Windows\System32\OpenSSH\ssh.exe" ...` then it works fine. So my question is this:

Which part of the system (Git Bash, Windows SSH, Windows Terminal, etc.) should be setting the correct TERM? This doesn't seem like a good default experience (in fact, the default experience even uses the Git Bash version of SSH, but that's another story).

How do I know for which applications TERM needs to be set to something other than the default?

> For what it's worth, I see egregious artifacts when I run it using cygwin SSH to a linux machine, even outside of Windows Terminal;

I've had similar issues for a long time, where the screen is not cleared properly. I used to use ConEmu with Git Bash, and when I SSH'd into a machine and exec'd into a Docker container, I saw this type of problem. I never found a solution.

Anyway, I think it's clear that there are some serious issues with these older versions of Cygwin/MSYS2 (or whatever it's called), so for now I'm more interested in finding a clean solution for running Windows SSH ahead of Git Bash SSH, with the correct TERM set.

Thanks.

**Comment by glen-84** [comment]
I noticed the following in the Git for Windows installer:

![image](https://user-images.githubusercontent.com/261509/78369579-b0984e00-75c5-11ea-8acf-09811cb8e784.png)

When I run Windows SSH using something like `winpty "C:\Windows\System32\OpenSSH\ssh.exe" ...`, then things also work correctly.

I've set up the following alias in my `.bashrc` file:

```sh
alias ssh='winpty "C:\Windows\System32\OpenSSH\ssh.exe"'
```

Still not an ideal default experience for many others who will possibly encounter these issues, but at least it's working now.

**Comment by DHowett-MSFT** [comment]
Thanks for following up! Once Cygwin 3.1 makes its way up to git's msys2 fork, a lot of this should simply go away. The latest version allows conhost to parse VT sequences instead of implementing an intermediary. That lets them completely deprecate the `cygwin` term value :smile:
