### ISSUE TITLE
Use tab-bar/title bar for dragging window around

### ISSUE THREAD

**Issue by Paul-Weisser** [microsoft/terminal#564]
I think its really nice that you can put the terminal-tabs in your titlebar but I got an issue there.

You can't move the window around klicking on the blank space in the the-bar to move the window around (highlighted in the screenshot). 

Since people are moving their terminal quite often it would be nice to offer this space, so you can drag your terminal around. 

![grafik](https://user-images.githubusercontent.com/34196171/57354083-ccebfa80-716a-11e9-91ac-55747463a95c.png)

**Comment by glen-84** [comment]
Duplicate of #528 (?).

**Comment by Paul-Weisser** [comment]
> 
> 
> Duplicate of #528 (?).

No, the issue you mentioned describes losing focus of the current terminal-tab.

This issue is about dragging the whole window around.

**Comment by miloush** [comment]
One of the main reasons I was not happy with sets was that especially for console windows, I could not see the whole window title.

![image](https://user-images.githubusercontent.com/10546952/57371083-1f8cdd00-7192-11e9-992b-ba4c906d5b71.png)

I would prefer much more if the free space was used for window titles when needed.

**Comment by oising** [comment]
@Paul-Weisser It *is* a duplicate of #528 -- that issues describes trying to trying to drag the window but it doesn't work and _additionally_ blocks the current tab.

**Comment by Paul-Weisser** [comment]
> 
> 
> @Paul-Weisser It _is_ a duplicate of #528 -- that issue specifically explains that when one is trying to drag the window to move it, it doesn't work and _additionally_ this action blocks the current tab for input.

please read #528 to the end as  zadjii-msft is adressing this issue as an external issue...

**Comment by zadjii-msft** [comment]
Okay, IMO, lets leave #528 as "the tab row steals focus from the terminal".

This is now the "use the tab bar to drag the window" thread.

**Comment by zadjii-msft** [comment]
As I mentioned in #528, this is a bug with XAML Islands currently, where we're not getting WM_NCHITTEST messages for the XAML Islands area (which hosts the tab control). They're working on fixing that for us - once we get those messages, we'll be able to hittest ourselves against the actual tabs, vs the "background" of the tabs.

**Comment by notlaforge** [comment]
@zadjii-msft does that mean the fix will require another Windows build?

**Comment by fearthecowboy** [comment]
I had a couple thoughts on temporary work around for this:

- is it possible to move the `+v` control to the left side, and then have the tab bar no wider than the tabs themselves?
- or, can an additional invisible control be placed over top the empty area in the tab bar that can give you the message to allow you to drag?

**Comment by DHowett-MSFT** [comment]
This'll be addressed by #929.

**Comment by DHowett-MSFT** [comment]
Moved into v0.3, the second public preview.

**Comment by sandercox** [comment]
hoping that would also fix the ability to drag just above the tab.. as I'm used to dragging from there with apps like Chrome as well.

**Comment by BernierCR** [comment]
Hmm thanks for the work. 

But it seems that so far, all that has really happened is moving the drop down menu closer to the tabs. You can still only drag from the small area to the right of the drop down menu. If you have just one or two tabs, this area is now a bit larger then it was before. But once you get to 3 or 4 tabs, it's just as small again. 

I understand software development takes time. I do it myself. But the news exaggerated this. Keep up the good work anyways. 

But let me know when you can drag the individual tabs around, when you can rename the tabs with right click, not have to mess with programmatic title manipulations, and when you can drag the whole window around by the area above the tabs. 

Now that would be news worthy.

**Comment by gregpakes** [comment]
Agree with @BernierCR.  This update is an improvement, but it still doesn't behave like other tabbed applications.

For example, in chrome, you can drag the window by clicking the small space above any tab.  That still doesn't work in the terminal.

![image](https://user-images.githubusercontent.com/102243/62498065-4f935d00-b821-11e9-8bd5-c5bcac3fa85b.png)
