### ISSUE TITLE
Vim.exe HiDPI buffer size / cursor positioning

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/terminal#71]
_From @parkovski on November 28, 2017 18:56_

Originally posted [here](https://github.com/Microsoft/WSL/issues/2701).

I'm on Win10 build 1709, having an issue with a recent vim patch enabling `termguicolors` when maximized on a HiDPI scaled screen.

Here is what it looks like opening a file and typing `k` to move up a line (should do nothing on the first line):
![console](https://user-images.githubusercontent.com/1094150/33338113-436e6ba2-d432-11e7-9437-e3bcccb887c6.png)

Here is what it looks like scrolling down and trying to use the command line:
![console2](https://user-images.githubusercontent.com/1094150/33338215-92a0a582-d432-11e7-94ac-5ab49dd57f54.png)

I'm using PowerShell 6 RC, but this happens in Windows PowerShell too. You can see how maximizing the console cuts off a line at the bottom of the screen, and the scroll bar on the right is spilling over onto the next screen.

My setup is a Surface Pro 4 with a standard DPI external monitor - the issue only happens when I start vim in an unmaximized console and then maximize it on the Surface (HiDPI) screen. The console spills over to the next screen and it seems like the buffer is shifted up by one line - `ggk` shows a white line at the top with no line number, and `Goj` makes inserted text appear on the line above where it's supposed to be.

After it's glitched out like this, unmaximizing the Window makes it even worse, kind of like @9a3eedi's tmux in the thread linked at the top, and `Ctrl-L` to redraw the screen doesn't fix it.

I noticed a similar off-by-one bug at the bottom of the console buffer while working on ANSI input for PSReadLine, but can't be sure if it's my bug or this one.

[Here is a copy of my patched vim.exe](https://1drv.ms/u/s!AtPZ-a4QMjWiivs0c4mfn2DimcOzRw) - hopefully this will help diagnose the problem. You may need these commands to make `tgc` work:
```vim
set t_Co=256
set t_8f="\e[38;2;%lu;%lu;%lum"
set t_8b="\e[48;2;%lu;%lu;%lum"
noremap! <Char-0x7F> <BS>
set tgc
```

_Copied from original issue: Microsoft/WSL#2704_

**Comment by bitcrazed** [comment]
_From @zadjii-msft on November 28, 2017 19:7_

Hmm. Do you happen to have a link to the "patch enabling termguicolors"? 

Am I correct that the unpatched version of vim.exe doesn't repro the issue?

I know there's some weird off-by-one-ness in `SetConsoleScreenBufferInfo*` - If you're calling that, you almost certainly need to increment `srWindow.Bottom` when roundtripping the `CONSOLE_SCREEN_BUFFER_INFO_EX`. See 
https://github.com/Microsoft/console/blob/master/tools/ColorTool/ColorTool/Program.cs#L187
for an example.

**Comment by bitcrazed** [comment]
_From @parkovski on November 28, 2017 19:37_

Sure, it's [this vim PR](https://github.com/vim/vim/pull/2060). If that patch has an off-by-one bug, I'm still confused by the maximizing behavior. If I maximize the Window on a standard DPI screen, it fills the whole screen area like I'd expect, but on the Surface screen there's a gap at the bottom and the right edge spills off the side (screenshots show this). And the fact that the glitch only happens on the HiDPI screen makes it seem like it might have to do with the maximizing behavior doing one thing but reporting another.

**Comment by bitcrazed** [comment]
_From @zadjii-msft on November 28, 2017 20:34_

Okay, sorry for my lack of knowledge on the specifics, but does vim.exe run inside of conhost.exe (responsible for cmd.exe, powershell.exe, wsl.exe, ubuntu.exe, etc) or does it draw it's own UI and window?

HiDPI is one of the great banes of our existence, and these kinds of bugs are terribly notorious to track down and often times change wildly from build to build, so I just want to get as much detail as I can.

**Comment by bitcrazed** [comment]
_From @parkovski on November 30, 2017 18:38_

It runs inside conhost, and it uses an alternate screen buffer to not overwrite the main one used by the shell, which is something else I've noticed - if you maximize the window with vim open and then exit vim, the console window shrinks back to the pre-maximized size because (I think) the original screen buffer doesn't resize when the window changes size. That happens regardless of DPI scaling, but only on Windows vim, not Linux/WSL.

**Comment by bitcrazed** [comment]
_From @zadjii-msft on November 30, 2017 19:24_

Thanks for clearing that up! I didn't realize that anyone really used the [CreateConsoleScreenBuffer](https://docs.microsoft.com/en-us/windows/console/createconsolescreenbuffer) API in the wild. That would explain the behavior you referenced, seperate buffers created with CreateConsoleScreenBuffer are pretty much left alone from one another, while alternate buffers created by WSL are more closely tied to the buffer that created them.

I've filed a bug to investigate further. We'll keep you posted :)

**Comment by bitcrazed** [comment]
_From @miniksa on December 4, 2017 17:52_

@parkovski, I'm not seeing the gap at the bottom on my High DPI display.

Can you tell me the exact pixel dimensions of the monitor and the scaling factor being used?

**Comment by bitcrazed** [comment]
_From @parkovski on December 4, 2017 19:40_

Sure, it's a Surface Pro 4, 2736x1824px, 200% scaling, and I'm using the [Fira Mono](https://github.com/mozilla/Fira) font, console size 16.

My second screen is 1920x1080, 100% scaling, and it's set to the primary monitor. I'll check if it happens when that one isn't attached, just have to log out first.

**Comment by bitcrazed** [comment]
_From @parkovski on December 4, 2017 20:6_

Ok - when I log in with the standard DPI screen as primary, the screenshots I posted above are what happen.

When I log in without the extra monitor attached, everything works fine until I attach the second screen - then I get the buffer glitches on the second screen, but not on the surface screen (so this seems to happen for DPI scales that are *not* the one the login session was started with). The window maximizes to the right size though in this case on the second (standard DPI) screen, even though the buffer is glitchy. The buffer is not glitchy on the Surface screen, but the window maximizes to the wrong size, but a different wrong size than when I start my login session on the second screen:

![console](https://user-images.githubusercontent.com/1094150/33572967-babe1c34-d8f1-11e7-8157-7df9180c83d2.png)

So it's kind of the opposite from before - instead of hanging over the right edge, there's a gap at the right now, and a tiny, maybe 1px gap at the bottom instead of a whole line.

Hope this helps.

**Comment by bitcrazed** [comment]
_From @miniksa on December 5, 2017 17:15_

Can you get this to happen with a standard console host running stock CMD/Powershell or with a production version of Vim?

**Comment by bitcrazed** [comment]
_From @parkovski on December 5, 2017 19:6_

It does happen with regular Windows PowerShell and cmd, interestingly there are no gaps or buffer glitches on my Surface screen with my font set to Consolas although I get a horizontal scroll bar instead and the ex (`:`) command line is behind the scroll bar. With Consolas the maximized window has gaps on my external standard DPI monitor. There are no buffer glitches with stock vim (or my patched vim with tgc off), but the window still maximizes to the wrong size with with gaps.

I also tested the console mode with [this utility](https://github.com/parkovski/isvt/blob/master/isvt.cpp). Stock vim is
```
Attached to process 5004.
cur[in]  = 0x1F8
         = ENABLE_WINDOW_INPUT | ENABLE_MOUSE_INPUT | ENABLE_INSERT_MODE | ENABLE_QUICK_EDIT_MODE | ENABLE_AUTO_POSITION
cur[out] = 0x4
         = ENABLE_VIRTUAL_TERMINAL_PROCESSING
```
My patched vim is
```
Attached to process 948.
cur[in]  = 0x1F8
         = ENABLE_WINDOW_INPUT | ENABLE_MOUSE_INPUT | ENABLE_INSERT_MODE | ENABLE_QUICK_EDIT_MODE | ENABLE_AUTO_POSITION
cur[out] = 0x5
         = ENABLE_PROCESSED_OUTPUT | ENABLE_VIRTUAL_TERMINAL_PROCESSING
```

**Comment by bitcrazed** [comment]
_From @miniksa on December 5, 2017 19:43_

OK let me try to unpack all of this.

There's one issue with the stock everything. Stock CMD, stock font (Consolas), stock Vim (of some version, please provide me the version number/download link). And that's that maximizing the window on a High DPI monitor (2736x1824px, 200% scaling) with a screen buffer created with CreateConsoleScreenBuffer() API seems to leave a gap around the frame of the window. Correct?

Then there's a second issue. Stock CMD, custom font (Fira Mono), stock Vim (hopefully same version). And maximizing that window on a High DPI monitor (2736x1824px, 200% scaling) with a screen buffer created with CreateConsoleScreenBuffer() API hides part of the buffer behind the scroll bar. Correct?

Then there's a third issue. Stock CMD, stock font (Consolas), custom built Vim (of your own patch). And maximizing that window on the High DPI monitor with the CreateConsoleScreenBuffer() buffer has a problem with the scrolling. Correct?

**Comment by bitcrazed** [comment]
_From @parkovski on December 5, 2017 21:36_

Sorry it's getting so complicated. I'll try to make this as reproducible as possible. [This is the stock vim I'm using](https://github.com/vim/vim-win32-installer/releases/tag/v8.0.0003)

First issue - stock cmd, stock font (Consolas 14), stock vim from above link. I'm running vim with "-u nul -i nul" so it doesn't load my .vimrc or .viminfo. Move the console to the primary standard DPI monitor, then move it back to the HiDPI Surface screen and maximize it. Then run "vim -u nul -i nul" _after_ maximizing the window. I'm seeing gaps around the window at this point. If I leave the window on the surface screen, quit vim and start it again, the size is fine. If I move it to the standard DPI screen and back to the HiDPI screen, maximize, and then start vim again, the gaps come back. After some more testing, it looks like the font does *not* affect this - the same happens with Consolas and Fira Mono (exact same steps). It looks like this:
![issue1](https://user-images.githubusercontent.com/1094150/33630573-1831d896-d9c5-11e7-8198-b1cac2a4e8aa.png)

When I mentioned that quitting vim and starting it again with the window still maximized has the correct size - that is true, every other time. Leaving the window in place, on the surface screen, after it has been on the standard DPI screen, start vim and quit repeatedly. It alternates between the correct maximized size and gaps as I posted in the screenshot.

Second issue with the scroll bars seems related to the "Wrap text on output" option. My cmd window does not have that option set; my PowerShell (Windows, not Core) does. In this case, using PowerShell with the option set, same steps as above, move the console to the standard DPI screen and then back to the HiDPI screen. Maximize it, and then open vim (`-u nul -i nul`). The first time, Consolas has only a horizontal scrollbar; Fira Mono has both horizontal and vertical scrollbars, but no part of vim is hidden behind them. I think that had to do with the patched vim, I'll look into that later. Exiting and restarting vim with the window unmoved, it will alternate between the correct size and gaps like above. Moving it to the standard DPI screen and back again will show the scroll bars one more time. This is Windows PowerShell, Consolas 14, vim from above link with no vimrc/viminfo, wrap text on output enabled, first time opened on HiDPI screen after coming from standard DPI screen:
![issue2](https://user-images.githubusercontent.com/1094150/33632033-a240e6ea-d9c9-11e7-9fbf-ed7b7c25c9f4.png)

I'll try to come up with reproducible steps for the patched vim/glitchy buffer issue later. This covers everything I'm seeing with stock everything.

**Comment by bitcrazed** [comment]
_From @miniksa on December 5, 2017 21:39_

Wonderful, thanks. I moved on to stare at another bug at this exact moment, but I'll circle back to this when that one is done. Your effort on laying this out cleanly is much appreciated!

**Comment by bitcrazed** [comment]
_From @miniksa on December 8, 2017 18:9_

@parkovski I just want to let you know that I'm still finishing up the other bug I'm working on and probably won't get to this one by the time I leave today. I have some scheduled vacation coming up starting Monday as do many of my co-workers and peers for the holiday season. As such, I'd just like to instill that this bug is still on our queue of things to do, but we may not get to it for a few weeks. I apologize for the inconvenience and would like to reiterate my appreciation for your efforts in helping us narrow this down to an easily reproducible set of steps.

**Comment by bitcrazed** [comment]
_From @parkovski on December 8, 2017 19:34_

No problem, it's pretty easy to work around for now. I probably won't get the fix until the next major update anyways since I'm not running insider builds.

**Comment by parkovski** [comment]
Just wanted to bring this back up - I am still getting gaps when moving the console to the other screen. There is another issue I've noticed around secondary buffer size that may/may not be related, going to open another issue for it.

**Comment by miniksa** [comment]
This bug is still parked on my plate. It's just been too low a priority versus other things I have going on (visual graphical glitch is a way lower priority than crashes and API processing issues.)

I intend to look at it, but it's going to just take time.

**Comment by parkovski** [comment]
No problem, just noticed it again recently and wanted to make sure it didn't get lost.

**Comment by miniksa** [comment]
It's cool. We don't really lose things as much as we have literally thousands of voices talking to us all the time. We appreciate your patience here.

**Comment by NicTanghe** [comment]
i remember there being a similar issue with cmder i'm 90% sure this was related to some changes windows made in 1709 and it should be fixed now.

**Comment by zadjii-msft** [comment]
Hey so I'm playing with a fairly recent vim (8.2.3412), on Windows 11, in conhost (not the Terminal), and I can't seem to get any of the repros in this thread to happen anymore. given the thread's more than 4 years old at this point, who knows what could have fixed this. @parkovski You still seeing this?
